(()=>{
  "use strict";
  const TAU=Math.PI*2,canvas=document.querySelector("#game"),ctx=canvas.getContext("2d",{alpha:false});
  const atlas=new Image(),water=new Image(),finzoClosed=new Image();
  atlas.src="assets/ocean-atlas.png";water.src="assets/ocean-water.png";finzoClosed.src="assets/finzo-closed.png";
  const $=s=>document.querySelector(s);
  const ui={menu:$("#menu"),hud:$("#hud"),over:$("#gameover"),pause:$("#pause"),clear:$("#level-clear"),play:$("#play-btn"),again:$("#again-btn"),home:$("#home-btn"),pauseBtn:$("#pause-btn"),resume:$("#resume-btn"),quit:$("#quit-btn"),next:$("#next-btn"),score:$("#score"),size:$("#size"),level:$("#level"),growth:$("#growth-fill"),growthLabel:$("#growth-label"),finalScore:$("#final-score"),finalSize:$("#final-size"),endTitle:$("#end-title"),clearEyebrow:$("#clear-eyebrow"),clearTitle:$("#clear-title"),clearCopy:$("#clear-copy"),message:$("#message"),mobile:$("#mobile-controls"),joystick:$("#joystick")};
  const input={keys:new Set(),touches:new Map(),stick:{x:0,y:0,pointerId:null}};
  const state={running:false,paused:false,campaignWon:false,last:0,time:0,score:0,totalScore:0,eaten:0,level:1,camera:{x:0,y:0},player:null,creatures:[],obstacles:[],particles:[],pattern:null,messageTimer:0,loopToken:0,winSize:108};
  let vw=innerWidth,vh=innerHeight,dpr=1,audio=null;
  const coarse=matchMedia("(pointer: coarse)").matches||/(?:^|[?&])mobile=1/.test(location.search);
  const best={score:Number(localStorage.getItem("piranha3-score")||0),level:Number(localStorage.getItem("piranha3-level")||1)};
  const show=(node,on)=>node.classList.toggle("active",on),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),random=(a,b)=>a+Math.random()*(b-a);
  function overlap(a,b,arx,ary,brx,bry){const dx=(a.x-b.x)/Math.max(1,arx+brx),dy=(a.y-b.y)/Math.max(1,ary+bry);return dx*dx+dy*dy<1}
  function resize(){vw=innerWidth;vh=innerHeight;dpr=Math.min(devicePixelRatio||1,coarse?1.25:1.7);canvas.width=Math.round(vw*dpr);canvas.height=Math.round(vh*dpr);canvas.style.width=vw+"px";canvas.style.height=vh+"px";ctx.setTransform(dpr,0,0,dpr,0,0);state.pattern=null;state.winSize=clamp(Math.min(vw*.28,vh*.31),96,126)}
  function waterline(){return clamp(vh*.22,104,210)}
  function safeTop(){return Math.max(coarse?clamp(vh*.13,72,110):72,waterline()+18)}
  function initAudio(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume()}
  function sound(kind){if(!audio)return;const now=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);if(kind==="bite"){o.type="square";o.frequency.setValueAtTime(270,now);o.frequency.exponentialRampToValueAtTime(670,now+.08)}else if(kind==="grow"||kind==="win"){o.type="triangle";o.frequency.setValueAtTime(240,now);o.frequency.exponentialRampToValueAtTime(kind==="win"?1180:850,now+(kind==="win"?.5:.18))}else{o.type="sawtooth";o.frequency.setValueAtTime(145,now);o.frequency.exponentialRampToValueAtTime(38,now+.48)}g.gain.setValueAtTime(kind==="death"?.14:.075,now);g.gain.exponentialRampToValueAtTime(.001,now+(kind==="win"?.55:kind==="death"?.5:.16));o.start(now);o.stop(now+(kind==="win"?.58:kind==="death"?.52:.18))}
  function announce(text){ui.message.textContent=text;ui.message.classList.add("show");state.messageTimer=1.15}
  function difficulty(){return 1+(state.level-1)*.12+Math.min(.5,state.time/115)}
  function creatureTarget(){return Math.min(coarse?18:25,(coarse?8:11)+state.level+Math.floor(state.time/13))}
  function obstacleTarget(){return Math.min(coarse?6:8,3+Math.floor(state.time/28)+Math.floor(state.level/3))}
  function makeCreature(initial=false,forced=null){const roll=Math.random(),early=state.time<11,smallChance=clamp((early?.91:.8)-state.time*.0035-(state.level-1)*.045,.43,.91),flyerChance=state.level>=3&&state.time>14?clamp(.055+(state.level-3)*.045+Math.min(.04,state.time/300),.055,.2):0;let kind=forced;if(!kind){if(Math.random()<flyerChance)kind="flyer";else if(roll<smallChance)kind="small";else{const r=(roll-smallChance)/(1-smallChance);kind=r<.34?"piranha":r<.6?"shark":r<.8?"lionfish":"jelly"}}const scale=1+(state.level-1)*.055;const size=(kind==="small"?random(12,24):kind==="piranha"?random(31,44):kind==="shark"?random(53,73):kind==="lionfish"?random(37,50):kind==="flyer"?random(38,54):random(28,41))*scale;const x=initial?state.camera.x+random(vw*.36,vw*1.75):state.camera.x+vw*.62+random(100,380),top=-vh/2+safeTop()+size*.55,baseY=kind==="flyer"?random(Math.max(top,vh*.1),vh*.27):random(kind==="jelly"?Math.max(0,top):top,vh*.34),speed=(kind==="small"?random(78,120):kind==="shark"?random(118,160):kind==="flyer"?random(132,178):random(96,142))*difficulty();return{kind,x,y:baseY,baseY,size,heading:Math.PI,speed,phase:random(0,TAU),alive:true,flightAge:0,flightDuration:random(2.7,3.6),jumpHeight:random(vh*.48,vh*.62),flightTilt:0}}
  function makeObstacle(initial=false){const r=Math.random(),kind=r<.43?"coral":r<.75?"shell":"treasure";return{kind,x:initial?state.camera.x+random(vw*.4,vw*2.1):state.camera.x+vw*.62+random(170,540),y:vh*.36,size:kind==="coral"?random(54,77):kind==="shell"?random(42,60):random(47,63),phase:random(0,TAU),alive:true}}
  function resetLevel(){state.time=0;state.score=0;state.eaten=0;state.messageTimer=0;state.player={x:-vw*.2,y:0,size:30+Math.min(8,(state.level-1)*1.5),angle:0,bite:0,alive:true};state.camera.x=0;state.camera.y=0;state.creatures.length=0;state.obstacles.length=0;state.particles.length=0;for(let i=0;i<creatureTarget();i++)state.creatures.push(makeCreature(true,"small"));["treasure","coral","shell"].forEach((kind,i)=>{const o=makeObstacle(true);o.kind=kind;o.x=vw*(.82+i*.61);state.obstacles.push(o)});updateHud()}
  function beginLevel(){resetLevel();input.keys.clear();input.touches.clear();resetStick();state.running=true;state.paused=false;state.last=performance.now();state.loopToken++;show(ui.menu,false);show(ui.over,false);show(ui.pause,false);show(ui.clear,false);show(ui.hud,true);ui.hud.setAttribute("aria-hidden","false");ui.mobile.classList.toggle("active",coarse);ui.mobile.setAttribute("aria-hidden",String(!coarse));const token=state.loopToken;requestAnimationFrame(t=>loop(t,token));announce("OCEAN "+state.level+(state.level>=3?" — WATCH THE SKY!":" — EAT WHAT IS SMALLER"))}
  function start(){initAudio();state.level=1;state.totalScore=0;state.campaignWon=false;beginLevel()}
  function finish(reason){if(!state.running)return;state.running=false;state.loopToken++;state.player.alive=false;sound("death");burst(state.player.x,state.player.y,"#00f5ff",30);best.score=Math.max(best.score,state.totalScore+state.score);localStorage.setItem("piranha3-score",String(best.score));const titles={jelly:"POISONED BY A JELLYFISH!",shark:"THE SHARK WAS BIGGER",piranha:"PIRANHA ATTACK!",lionfish:"VENOMOUS LIONFISH!",flyer:"SKY HUNTER DIVE!",coral:"CRASHED INTO CORAL",shell:"A SHELL STOPPED FINZO"};ui.endTitle.textContent=titles[reason]||"YOU WERE EATEN";ui.finalScore.textContent=(state.totalScore+state.score).toLocaleString("en-US");ui.finalSize.textContent=`Final size: ${(state.player.size/30).toFixed(1)}× · ${state.eaten} fish eaten`;show(ui.over,true);show(ui.hud,false);ui.mobile.classList.remove("active")}
  function winLevel(){if(!state.running)return;state.running=false;state.loopToken++;state.totalScore+=state.score;state.campaignWon=state.level>=5;best.level=Math.max(best.level,Math.min(5,state.level+1));best.score=Math.max(best.score,state.totalScore);localStorage.setItem("piranha3-level",String(best.level));localStorage.setItem("piranha3-score",String(best.score));sound("win");burst(state.player.x,state.player.y,"#9dff00",52);draw();if(state.campaignWon){ui.clearEyebrow.textContent="ULTIMATE OCEAN LEGEND";ui.clearTitle.textContent="ALL FIVE OCEANS CONQUERED!";ui.clearCopy.textContent="Finzo has become the brightest apex creature in the fluorescent deep. You won Piranha 3!";ui.next.textContent="PLAY AGAIN"}else{ui.clearEyebrow.textContent="APEX OF THE OCEAN";ui.clearTitle.textContent="OCEAN "+state.level+" CONQUERED!";ui.clearCopy.textContent="Finzo now enters a brighter, faster and more dangerous ocean.";ui.next.textContent="ENTER OCEAN "+(state.level+1)}show(ui.clear,true);show(ui.hud,false);ui.mobile.classList.remove("active")}
  function nextLevel(){if(state.campaignWon){state.level=1;state.totalScore=0;state.campaignWon=false}else state.level++;beginLevel()}
  function movement(){let x=input.stick.x,y=input.stick.y;for(const k of input.keys){if(k==="ArrowLeft"||k==="a")x--;if(k==="ArrowRight"||k==="d")x++;if(k==="ArrowUp"||k==="w")y--;if(k==="ArrowDown"||k==="s")y++}for(const d of input.touches.values()){if(d==="left")x--;if(d==="right")x++;if(d==="up")y--;if(d==="down")y++}const l=Math.hypot(x,y);return l>1?{x:x/l,y:y/l}:{x,y}}
  function canEat(fish){return fish.kind!=="jelly"&&state.player.size>fish.size*1.18}
  function update(dt){state.time+=dt;const p=state.player,m=movement(),scroll=Math.min(285,126+state.time*1.1+(state.level-1)*14);state.camera.x+=scroll*dt;p.x+=(scroll+m.x*470)*dt;p.y+=m.y*590*dt;const playerRightMargin=Math.max(34,p.size*1.08);p.x=clamp(p.x,state.camera.x-vw*.37,state.camera.x+vw*.5-playerRightMargin);p.y=clamp(p.y,-vh/2+safeTop()+p.size*.56,vh*.35);p.angle+=(m.y*.21-p.angle)*Math.min(1,dt*58);p.bite=Math.max(0,p.bite-dt);
    for(const f of state.creatures){f.phase+=dt*(f.kind==="jelly"?2.2:5);if(f.kind==="flyer"){f.x-=f.speed*dt;f.flightAge+=dt;const t=clamp(f.flightAge/f.flightDuration,0,1);let lift;if(t<.58){const q=t/.58;lift=Math.sin(q*Math.PI*.5);f.flightTilt=.42*(1-q)}else{const q=(t-.58)/.42;lift=1-q*q;f.flightTilt=-.92*q}f.y=f.baseY-f.jumpHeight*lift;if(t>=1){f.flightAge=0;f.flightDuration=random(2.7,3.6);f.jumpHeight=random(vh*.48,vh*.62);f.flightTilt=0}}else if(f.kind==="jelly"){f.x-=f.speed*.28*dt;f.y+=Math.sin(f.phase)*10*dt}else{f.x-=f.speed*dt;f.y+=Math.sin(f.phase*.55)*5*dt}if(overlap(p,f,p.size*.58,p.size*.3,f.size*.57,f.size*.28)){if(canEat(f))eat(f);else{finish(f.kind);return}}}
    for(const o of state.obstacles){if(!o.alive)continue;const treasure=o.kind==="treasure",touch=overlap(p,o,p.size*.55,p.size*.31,o.size*(treasure?.42:.36),o.size*(treasure?.34:.32));if(touch){if(treasure)collect(o);else{finish(o.kind);return}}}
    if(p.size>=state.winSize){winLevel();return}state.creatures=state.creatures.filter(f=>f.alive&&f.x>state.camera.x-vw*.72);state.obstacles=state.obstacles.filter(o=>o.alive&&o.x>state.camera.x-vw*.72);while(state.creatures.length<creatureTarget())state.creatures.push(makeCreature());while(state.obstacles.length<obstacleTarget())state.obstacles.push(makeObstacle());updateParticles(dt);if(state.messageTimer>0&&(state.messageTimer-=dt)<=0)ui.message.classList.remove("show");updateHud()}
  function eat(f){f.alive=false;state.eaten++;const hostile=f.kind!=="small",gain=Math.round(f.size*(hostile?2.4:1));state.score+=gain;const before=state.player.size;state.player.size=Math.min(state.winSize+4,state.player.size+(hostile?2.5:1.05)+f.size*(hostile?.075:.035));state.player.bite=.28;sound("bite");burst(f.x,f.y,hostile?"#ff2bd6":"#fff200",hostile?19:11);if(hostile)announce("FINZO ATE A "+(f.kind==="flyer"?"SKY HUNTER":f.kind.toUpperCase())+"!");else if(Math.floor(before/18)<Math.floor(state.player.size/18)){sound("grow");announce("FINZO GREW BIGGER!")}}
  function collect(o){o.alive=false;state.score+=85;state.player.size=Math.min(state.winSize+4,state.player.size+4.7);state.player.bite=.25;sound("grow");burst(o.x,o.y,"#ffe45d",17);announce("TREASURE — EXTRA GROWTH!")}
  function burst(x,y,color,count){for(let i=0;i<count;i++){const a=random(0,TAU),s=random(35,155);state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:random(.25,.68),max:.68,color,size:random(2,6)})}}
  function updateParticles(dt){for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.08,dt);p.vy*=Math.pow(.08,dt);p.life-=dt}state.particles=state.particles.filter(p=>p.life>0)}
  function updateHud(){const progress=clamp((state.player.size-30)/(state.winSize-30),0,1);ui.score.textContent=(state.totalScore+state.score).toLocaleString("en-US");ui.size.textContent=(state.player.size/30).toFixed(1)+"×";ui.level.textContent=state.level;ui.growth.style.width=Math.round(progress*100)+"%";ui.growthLabel.textContent=Math.round(progress*100)+"% TO DOMINANCE"}
  function vectorCell(index,x,y,w,h,flip=false,alpha=1){ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.globalAlpha=alpha;const body=(fill,stroke="#02072c")=>{ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=Math.max(2,h*.045);ctx.beginPath();ctx.ellipse(0,0,w*.31,h*.34,0,0,TAU);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(-w*.27,0);ctx.lineTo(-w*.48,-h*.3);ctx.lineTo(-w*.46,h*.3);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(w*.19,-h*.09,h*.075,0,TAU);ctx.fill();ctx.fillStyle="#071a31";ctx.beginPath();ctx.arc(w*.21,-h*.09,h*.035,0,TAU);ctx.fill()};if(index<=4||index===7){const colors=["#00f5ff","#fff200","#0077ff","#ff2bd6","#00a6ff","#ff4b00","#a338ff","#ff315f"];body(colors[index]||"#00f5ff");if(index===3){ctx.fillStyle="#fff";for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(w*(.08+i*.045),h*.08);ctx.lineTo(w*(.105+i*.045),h*.2);ctx.lineTo(w*(.13+i*.045),h*.08);ctx.fill()}}if(index===4){ctx.fillStyle="#e8f7ff";ctx.beginPath();ctx.moveTo(-w*.08,0);ctx.lineTo(w*.31,h*.28);ctx.lineTo(w*.28,h*.05);ctx.closePath();ctx.fill()}if(index===7){ctx.strokeStyle="#fff200";ctx.lineWidth=2;for(let i=-3;i<=3;i++){ctx.beginPath();ctx.moveTo(-w*.08,i*h*.065);ctx.lineTo(-w*.34,i*h*.12);ctx.stroke()}}}else if(index===5||index===6){ctx.fillStyle=index===5?"#ff2bd6":"#8b2bff";ctx.strokeStyle="#dffbff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-h*.12,w*.25,Math.PI,TAU);ctx.lineTo(w*.25,h*.06);ctx.lineTo(-w*.25,h*.06);ctx.closePath();ctx.fill();ctx.stroke();for(let i=-2;i<=2;i++){ctx.beginPath();ctx.moveTo(i*w*.09,h*.04);ctx.quadraticCurveTo(i*w*.1+Math.sin(state.time*5+i)*8,h*.25,i*w*.08,h*.43);ctx.stroke()}}else if(index===8){ctx.strokeStyle="#ff2bd6";ctx.lineWidth=w*.12;ctx.lineCap="round";for(let i=-2;i<=2;i++){ctx.beginPath();ctx.moveTo(i*w*.09,h*.42);ctx.quadraticCurveTo(i*w*.13,-h*.02,(i+(i%2?.4:-.35))*w*.1,-h*(.22+Math.abs(i)*.05));ctx.stroke()}}else if(index===9){ctx.fillStyle="#00f5ff";ctx.strokeStyle="#132169";ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,h*.08,w*.3,Math.PI,TAU);ctx.quadraticCurveTo(0,-h*.03,-w*.3,h*.08);ctx.fill();ctx.stroke();for(let i=-2;i<=2;i++){ctx.beginPath();ctx.moveTo(0,h*.04);ctx.lineTo(i*w*.12,-h*.16);ctx.stroke()}}else{ctx.fillStyle="#7e3f08";ctx.strokeStyle="#fff200";ctx.lineWidth=4;ctx.beginPath();ctx.rect(-w*.32,-h*.23,w*.64,h*.48);ctx.fill();ctx.stroke();ctx.fillStyle="#fff200";ctx.beginPath();ctx.arc(0,0,h*.08,0,TAU);ctx.fill()}ctx.restore()}
  function atlasCell(index,x,y,w,h,flip=false,alpha=1){vectorCell(index,x,y,w,h,flip,alpha);if(!atlas.complete||!atlas.naturalWidth)return false;const cw=atlas.naturalWidth/4,ch=atlas.naturalHeight/3;ctx.save();try{ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.globalAlpha=alpha;ctx.drawImage(atlas,index%4*cw,Math.floor(index/4)*ch,cw,ch,-w/2,-h/2,w,h);return true}catch(_error){return false}finally{ctx.restore()}}
  function fins(length,phase,flip,color){const beat=Math.sin(phase);ctx.save();if(flip)ctx.scale(-1,1);ctx.globalAlpha=.78;ctx.fillStyle=color;ctx.strokeStyle="rgba(227,255,255,.72)";ctx.lineWidth=Math.max(1.2,length*.018);ctx.beginPath();ctx.moveTo(-length*.39,-length*.12);ctx.quadraticCurveTo(-length*.63,-length*(.34+beat*.1),-length*.72,beat*length*.14);ctx.quadraticCurveTo(-length*.63,length*(.34-beat*.1),-length*.39,length*.12);ctx.closePath();ctx.fill();ctx.stroke();ctx.globalAlpha=.62;ctx.beginPath();ctx.moveTo(-length*.11,-length*.24);ctx.quadraticCurveTo(length*.02,-length*(.50+beat*.04),length*.16,-length*.24);ctx.closePath();ctx.fill();ctx.stroke();ctx.globalAlpha=.56;ctx.beginPath();ctx.ellipse(-length*.03,length*.2,length*.22,length*.07,beat*.32,0,TAU);ctx.fill();ctx.stroke();ctx.restore()}
  function fishPolish(kind,h,ratio,flip,phase){if(kind==="jelly")return;const w=h*ratio,front=w*.23;ctx.save();if(flip)ctx.scale(-1,1);ctx.lineCap="round";ctx.globalCompositeOperation="screen";ctx.strokeStyle=kind==="player"?"rgba(156,255,0,.92)":"rgba(219,255,255,.72)";ctx.lineWidth=Math.max(1.1,h*.025);ctx.beginPath();ctx.ellipse(-w*.03,-h*.11,w*.25,h*.17,-.08,Math.PI*1.08,Math.PI*1.86);ctx.stroke();ctx.globalCompositeOperation="source-over";ctx.strokeStyle="rgba(4,24,57,.62)";ctx.lineWidth=Math.max(1,h*.018);for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(front-i*h*.035,h*(.015+i*.025),h*(.11+i*.012),Math.PI*.63,Math.PI*1.26);ctx.stroke()}const colors=kind==="piranha"?["#ffef69","#43115f"]:kind==="lionfish"?["#fff0a8","#ff4938"]:kind==="shark"?["#b9f8ff","#27668d"]:["#fff568","#63fff2"];ctx.globalAlpha=.72;for(let i=0;i<5;i++){const px=-w*.18+i*w*.105,py=Math.sin(phase*.4+i*1.8)*h*.075;ctx.fillStyle=colors[i%2];ctx.beginPath();ctx.ellipse(px,py,h*.036,h*.058,-.35,0,TAU);ctx.fill()}ctx.globalAlpha=1;ctx.fillStyle="#ffffff";ctx.beginPath();ctx.arc(front+h*.072,-h*.105,Math.max(1.2,h*.025),0,TAU);ctx.fill();ctx.restore()}
  function drawSmallFishGraphic(h,flip,phase){const w=h*1.45;ctx.save();if(flip)ctx.scale(-1,1);ctx.lineJoin="round";ctx.strokeStyle="#051d43";ctx.lineWidth=Math.max(1.5,h*.04);const gold=Math.sin(phase*.19)>0;ctx.fillStyle=gold?"#fff13c":"#2df5ff";ctx.beginPath();ctx.moveTo(-w*.38,0);ctx.lineTo(-w*.62,-h*.31);ctx.lineTo(-w*.59,h*.31);ctx.closePath();ctx.fill();ctx.stroke();const g=ctx.createLinearGradient(0,-h*.38,0,h*.38);g.addColorStop(0,gold?"#fff978":"#a9ffff");g.addColorStop(.52,gold?"#ffbd20":"#00d5ff");g.addColorStop(1,gold?"#ff6c25":"#0874ff");ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(-w*.02,0,w*.39,h*.34,0,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle=gold?"#ff4b2e":"#9dff00";ctx.beginPath();ctx.moveTo(-w*.05,-h*.28);ctx.lineTo(w*.05,-h*.52);ctx.lineTo(w*.17,-h*.25);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="rgba(255,255,255,.58)";ctx.beginPath();ctx.ellipse(w*.04,-h*.13,w*.22,h*.075,-.12,0,TAU);ctx.fill();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(w*.24,-h*.09,h*.085,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle="#061b37";ctx.beginPath();ctx.arc(w*.265,-h*.09,h*.037,0,TAU);ctx.fill();ctx.strokeStyle="#09254c";ctx.lineWidth=Math.max(1,h*.025);ctx.beginPath();ctx.arc(w*.32,h*.05,h*.09,.35,1.65);ctx.stroke();ctx.restore()}
  function drawPiranhaGraphic(h,flip,phase){const w=h*1.62;ctx.save();if(flip)ctx.scale(-1,1);ctx.lineJoin="round";ctx.strokeStyle="#26083f";ctx.lineWidth=Math.max(2,h*.04);ctx.fillStyle="#d62be9";ctx.beginPath();ctx.moveTo(-w*.40,0);ctx.lineTo(-w*.67,-h*.38);ctx.lineTo(-w*.60,h*.39);ctx.closePath();ctx.fill();ctx.stroke();for(let i=0;i<6;i++){ctx.fillStyle=i%2?"#ffef58":"#ff38d6";ctx.beginPath();ctx.moveTo(-w*.24+i*w*.09,-h*.29);ctx.lineTo(-w*.19+i*w*.09,-h*(.53+(i%2)*.06));ctx.lineTo(-w*.12+i*w*.09,-h*.27);ctx.closePath();ctx.fill();ctx.stroke()}const g=ctx.createLinearGradient(0,-h*.42,0,h*.42);g.addColorStop(0,"#ff71e8");g.addColorStop(.45,"#c52ad7");g.addColorStop(1,"#5c168d");ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(-w*.39,0);ctx.bezierCurveTo(-w*.28,-h*.39,w*.21,-h*.48,w*.43,-h*.17);ctx.quadraticCurveTo(w*.56,0,w*.43,h*.22);ctx.bezierCurveTo(w*.16,h*.47,-w*.28,h*.39,-w*.39,0);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="rgba(255,239,86,.76)";for(let i=0;i<4;i++){ctx.beginPath();ctx.ellipse(-w*.19+i*w*.11,Math.sin(phase*.3+i)*h*.075,h*.045,h*.09,-.28,0,TAU);ctx.fill()}ctx.fillStyle="#fff";ctx.beginPath();ctx.ellipse(w*.19,-h*.15,h*.12,h*.145,0,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle="#16102b";ctx.beginPath();ctx.arc(w*.225,-h*.14,h*.055,0,TAU);ctx.fill();ctx.strokeStyle="#26083f";ctx.lineWidth=Math.max(2,h*.045);ctx.beginPath();ctx.moveTo(w*.07,-h*.30);ctx.lineTo(w*.30,-h*.22);ctx.stroke();ctx.fillStyle="#190719";ctx.beginPath();ctx.ellipse(w*.40,h*.08,w*.17,h*.22,-.04,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle="#fffbdc";for(let i=0;i<5;i++){const x=w*(.28+i*.055);ctx.beginPath();ctx.moveTo(x,-h*.105);ctx.lineTo(x+h*.04,h*.015);ctx.lineTo(x+h*.08,-h*.10);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(x,h*.255);ctx.lineTo(x+h*.04,h*.13);ctx.lineTo(x+h*.08,h*.25);ctx.closePath();ctx.fill()}ctx.restore()}
  function drawSharkGraphic(h,flip,phase){const w=h*2.05;ctx.save();if(flip)ctx.scale(-1,1);ctx.lineJoin="round";ctx.strokeStyle="#06283e";ctx.lineWidth=Math.max(2,h*.035);const finBeat=Math.sin(phase*1.5)*h*.04;ctx.fillStyle="#3d99c1";ctx.beginPath();ctx.moveTo(-w*.42,0);ctx.lineTo(-w*.68,-h*(.45+finBeat));ctx.lineTo(-w*.60,-h*.02);ctx.lineTo(-w*.67,h*(.43-finBeat));ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(-w*.05,-h*.29);ctx.lineTo(w*.03,-h*.74);ctx.lineTo(w*.18,-h*.28);ctx.closePath();ctx.fill();ctx.stroke();const g=ctx.createLinearGradient(0,-h*.45,0,h*.45);g.addColorStop(0,"#9eeeff");g.addColorStop(.47,"#368db9");g.addColorStop(.5,"#d8fbf6");g.addColorStop(1,"#8bc7ca");ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(-w*.45,0);ctx.bezierCurveTo(-w*.25,-h*.38,w*.24,-h*.39,w*.51,-h*.13);ctx.quadraticCurveTo(w*.61,-h*.015,w*.50,h*.18);ctx.bezierCurveTo(w*.17,h*.38,-w*.27,h*.31,-w*.45,0);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#2d7fa4";ctx.beginPath();ctx.moveTo(-w*.04,h*.22);ctx.lineTo(w*.10,h*.59);ctx.lineTo(w*.23,h*.22);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle="rgba(5,42,62,.72)";ctx.lineWidth=Math.max(1.3,h*.025);for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(w*(.20+i*.045),-h*.02);ctx.lineTo(w*(.17+i*.045),h*.13);ctx.stroke()}ctx.fillStyle="#fff";ctx.beginPath();ctx.ellipse(w*.34,-h*.13,h*.09,h*.11,0,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle="#071b2a";ctx.beginPath();ctx.arc(w*.37,-h*.13,h*.045,0,TAU);ctx.fill();ctx.strokeStyle="#06283e";ctx.lineWidth=Math.max(2,h*.04);ctx.beginPath();ctx.moveTo(w*.25,-h*.27);ctx.lineTo(w*.43,-h*.22);ctx.stroke();ctx.fillStyle="#06111c";ctx.beginPath();ctx.moveTo(w*.26,h*.06);ctx.quadraticCurveTo(w*.42,h*.25,w*.53,h*.04);ctx.quadraticCurveTo(w*.42,h*.14,w*.26,h*.06);ctx.fill();ctx.stroke();ctx.fillStyle="#fffde6";for(let i=0;i<4;i++){const x=w*(.31+i*.045);ctx.beginPath();ctx.moveTo(x,h*.095);ctx.lineTo(x+h*.035,h*.18);ctx.lineTo(x+h*.07,h*.09);ctx.closePath();ctx.fill()}ctx.restore()}
  function drawLionfishGraphic(h,flip,phase){const w=h*1.58;ctx.save();if(flip)ctx.scale(-1,1);ctx.lineCap="round";ctx.lineJoin="round";ctx.strokeStyle="#55142d";for(let i=0;i<13;i++){const a=-2.35+i*(4.7/12),len=h*(.66+(i%3)*.12),sx=-w*.05+Math.cos(a)*h*.18,sy=Math.sin(a)*h*.18;ctx.strokeStyle=i%2?"#fff2a8":"#ff4d38";ctx.lineWidth=Math.max(2,h*.045);ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(sx+Math.cos(a)*len,sy+Math.sin(a)*len);ctx.stroke()}ctx.fillStyle="rgba(255,118,51,.84)";for(const side of [-1,1]){ctx.beginPath();ctx.moveTo(-w*.08,side*h*.12);ctx.quadraticCurveTo(-w*.36,side*h*.72,w*.12,side*h*.46);ctx.lineTo(w*.08,side*h*.12);ctx.closePath();ctx.fill();ctx.strokeStyle="#fff0aa";ctx.stroke()}ctx.fillStyle="#ff6f36";ctx.beginPath();ctx.moveTo(-w*.38,0);ctx.lineTo(-w*.65,-h*.38);ctx.lineTo(-w*.59,h*.38);ctx.closePath();ctx.fill();ctx.strokeStyle="#55142d";ctx.lineWidth=Math.max(2,h*.04);ctx.stroke();const g=ctx.createLinearGradient(0,-h*.38,0,h*.38);g.addColorStop(0,"#ffb149");g.addColorStop(.5,"#f25539");g.addColorStop(1,"#a51e46");ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(0,0,w*.42,h*.39,0,0,TAU);ctx.fill();ctx.stroke();ctx.strokeStyle="#fff3ad";ctx.lineWidth=Math.max(2,h*.07);for(let i=-3;i<=3;i++){ctx.beginPath();ctx.moveTo(i*w*.09,-h*.31);ctx.lineTo((i+.22)*w*.09,h*.31);ctx.stroke()}ctx.fillStyle="#fff";ctx.beginPath();ctx.ellipse(w*.25,-h*.12,h*.105,h*.13,0,0,TAU);ctx.fill();ctx.strokeStyle="#55142d";ctx.lineWidth=Math.max(1.5,h*.03);ctx.stroke();ctx.fillStyle="#11122b";ctx.beginPath();ctx.arc(w*.285,-h*.12,h*.05,0,TAU);ctx.fill();ctx.strokeStyle="#3d1028";ctx.beginPath();ctx.arc(w*.36,h*.05,h*.09,.25,1.55);ctx.stroke();ctx.restore()}
  function drawFlyingFishGraphic(h,flip,phase){const w=h*1.72,beat=Math.sin(phase*2.25);ctx.save();if(flip)ctx.scale(-1,1);ctx.lineJoin="round";ctx.lineCap="round";ctx.strokeStyle="#07194c";ctx.lineWidth=Math.max(2,h*.038);ctx.fillStyle="#00ddff";ctx.beginPath();ctx.moveTo(-w*.39,0);ctx.lineTo(-w*.68,-h*.43);ctx.lineTo(-w*.58,-h*.03);ctx.lineTo(-w*.67,h*.40);ctx.closePath();ctx.fill();ctx.stroke();const wing=ctx.createLinearGradient(-w*.1,-h*.72,w*.28,h*.55);wing.addColorStop(0,"rgba(205,255,255,.95)");wing.addColorStop(.45,"rgba(0,245,255,.86)");wing.addColorStop(1,"rgba(157,255,0,.55)");ctx.fillStyle=wing;for(const side of [-1,1]){ctx.beginPath();ctx.moveTo(-w*.10,side*h*.08);ctx.quadraticCurveTo(-w*.03,side*h*(.74+beat*.07),w*.31,side*h*(.49+beat*.04));ctx.quadraticCurveTo(w*.18,side*h*.19,w*.07,side*h*.08);ctx.closePath();ctx.fill();ctx.stroke()}const body=ctx.createLinearGradient(0,-h*.4,0,h*.4);body.addColorStop(0,"#fff66b");body.addColorStop(.3,"#ff7040");body.addColorStop(.68,"#126dff");body.addColorStop(1,"#321488");ctx.fillStyle=body;ctx.beginPath();ctx.moveTo(-w*.4,0);ctx.bezierCurveTo(-w*.22,-h*.35,w*.22,-h*.42,w*.47,-h*.15);ctx.lineTo(w*.64,-h*.02);ctx.lineTo(w*.47,h*.16);ctx.bezierCurveTo(w*.18,h*.41,-w*.25,h*.34,-w*.4,0);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle="#9dff00";ctx.lineWidth=Math.max(2,h*.045);for(let i=-2;i<=2;i++){ctx.beginPath();ctx.moveTo(-w*.18+i*w*.105,-h*.26);ctx.lineTo(-w*.13+i*w*.105,h*.26);ctx.stroke()}ctx.fillStyle="#fff";ctx.beginPath();ctx.ellipse(w*.3,-h*.13,h*.11,h*.135,0,0,TAU);ctx.fill();ctx.strokeStyle="#07194c";ctx.lineWidth=Math.max(1.5,h*.027);ctx.stroke();ctx.fillStyle="#07162f";ctx.beginPath();ctx.arc(w*.335,-h*.13,h*.052,0,TAU);ctx.fill();ctx.strokeStyle="#07194c";ctx.lineWidth=Math.max(2,h*.035);ctx.beginPath();ctx.moveTo(w*.25,-h*.28);ctx.lineTo(w*.42,-h*.22);ctx.stroke();ctx.fillStyle="#08112f";ctx.beginPath();ctx.moveTo(w*.42,h*.02);ctx.lineTo(w*.61,-h*.01);ctx.lineTo(w*.47,h*.17);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#fffbd7";for(let i=0;i<3;i++){const x=w*(.45+i*.047);ctx.beginPath();ctx.moveTo(x,h*.025);ctx.lineTo(x+h*.035,h*.105);ctx.lineTo(x+h*.065,h*.018);ctx.closePath();ctx.fill()}ctx.restore()}
  function drawShellGraphic(x,y,s){ctx.save();ctx.translate(x,y+s*.22);ctx.fillStyle="rgba(1,13,50,.28)";ctx.beginPath();ctx.ellipse(0,s*.22,s*.48,s*.13,0,0,TAU);ctx.fill();const g=ctx.createRadialGradient(-s*.15,-s*.20,s*.04,0,0,s*.62);g.addColorStop(0,"#fff8c7");g.addColorStop(.43,"#ffbd77");g.addColorStop(1,"#bd4b8f");ctx.fillStyle=g;ctx.strokeStyle="#54215d";ctx.lineWidth=Math.max(2,s*.045);ctx.beginPath();ctx.moveTo(-s*.48,s*.18);ctx.quadraticCurveTo(-s*.43,-s*.48,0,-s*.55);ctx.quadraticCurveTo(s*.43,-s*.48,s*.48,s*.18);ctx.quadraticCurveTo(0,s*.36,-s*.48,s*.18);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle="rgba(116,45,88,.65)";ctx.lineWidth=Math.max(1.5,s*.026);for(let i=-3;i<=3;i++){ctx.beginPath();ctx.moveTo(0,-s*.48);ctx.quadraticCurveTo(i*s*.11,-s*.06,i*s*.14,s*.19);ctx.stroke()}ctx.fillStyle="#7d2c67";ctx.beginPath();ctx.ellipse(0,s*.17,s*.38,s*.105,0,0,TAU);ctx.fill();ctx.stroke();ctx.strokeStyle="rgba(255,255,219,.86)";ctx.lineWidth=Math.max(1.5,s*.025);ctx.beginPath();ctx.arc(-s*.12,-s*.23,s*.20,3.3,5.2);ctx.stroke();ctx.restore()}
  function drawBiteMouth(h,amount){const open=clamp(amount,0,1),x=h*.705,y=h*.058;ctx.save();ctx.translate(x,y);ctx.rotate(-.07);ctx.fillStyle="rgba(7,15,45,.96)";ctx.strokeStyle="#baffef";ctx.lineWidth=Math.max(1.2,h*.014);ctx.beginPath();ctx.ellipse(0,0,h*.082,h*(.024+.043*open),0,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle="#ff6fae";ctx.beginPath();ctx.ellipse(-h*.008,h*(.014+.016*open),h*.043,h*.014,0,0,TAU);ctx.fill();ctx.fillStyle="#fffbd9";ctx.beginPath();ctx.moveTo(-h*.027,-h*(.027+.018*open));ctx.lineTo(-h*.010,h*.001);ctx.lineTo(h*.008,-h*(.028+.018*open));ctx.closePath();ctx.fill();ctx.strokeStyle="#82fff4";ctx.beginPath();ctx.moveTo(-h*.085,h*.012);ctx.quadraticCurveTo(-h*.11,h*.038,-h*.12,h*.055);ctx.stroke();ctx.restore()}
  function drawCloud(x,y,scale,alpha){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);const g=ctx.createLinearGradient(0,-18,0,18);g.addColorStop(0,`rgba(255,255,255,${alpha})`);g.addColorStop(1,`rgba(232,218,255,${alpha*.62})`);ctx.fillStyle=g;ctx.shadowColor="rgba(255,198,246,.42)";ctx.shadowBlur=12;ctx.beginPath();ctx.ellipse(-28,6,29,12,0,0,TAU);ctx.ellipse(-8,-3,23,18,0,0,TAU);ctx.ellipse(14,2,30,15,0,0,TAU);ctx.ellipse(38,7,22,10,0,0,TAU);ctx.fill();ctx.restore()}
  function drawSky(){const line=waterline(),skyPalettes=[["#24005f","#ba257e","#ffad3f"],["#1d145f","#6f43dc","#ffc348"],["#4f064f","#e12677","#ff923f"],["#191359","#7d35cf","#ff76c8"],["#35115e","#dc305f","#ffd23f"]],p=skyPalettes[(state.level-1)%skyPalettes.length],g=ctx.createLinearGradient(0,0,0,line);g.addColorStop(0,p[0]);g.addColorStop(.58,p[1]);g.addColorStop(1,p[2]);ctx.fillStyle=g;ctx.fillRect(0,0,vw,line+7);const sunX=vw*.76,sunY=line*.45,sunR=Math.max(22,line*.23),sun=ctx.createRadialGradient(sunX,sunY,2,sunX,sunY,sunR*2.2);sun.addColorStop(0,"rgba(255,255,231,1)");sun.addColorStop(.32,"rgba(255,241,96,.9)");sun.addColorStop(1,"rgba(255,76,181,0)");ctx.fillStyle=sun;ctx.beginPath();ctx.arc(sunX,sunY,sunR*2.2,0,TAU);ctx.fill();ctx.fillStyle="#fffbd0";ctx.beginPath();ctx.arc(sunX,sunY,sunR*.76,0,TAU);ctx.fill();for(let i=0;i<7;i++){const speed=7+i*2.2,span=vw+300,raw=i*211+state.time*speed-state.camera.x*.012,x=(raw%span)-150,y=line*(.17+(i%3)*.21)+Math.sin(state.time*.2+i)*2.4;drawCloud(x,y,.56+(i%3)*.17,.62+(i%2)*.14)}ctx.fillStyle="rgba(40,18,88,.34)";for(let i=0;i<5;i++){const x=(i*287-state.camera.x*.018)%(vw+240)-120;ctx.beginPath();ctx.moveTo(x,line);ctx.lineTo(x+80,line*.73);ctx.lineTo(x+170,line);ctx.closePath();ctx.fill()}const haze=ctx.createLinearGradient(0,line-24,0,line+10);haze.addColorStop(0,"rgba(255,229,192,0)");haze.addColorStop(1,"rgba(219,255,255,.96)");ctx.fillStyle=haze;ctx.fillRect(0,line-24,vw,34)}
  function drawSurface(){const base=waterline()+Math.sin(state.time*1.7)*2,g=ctx.createLinearGradient(0,base-8,0,base+42);g.addColorStop(0,"rgba(226,255,255,.88)");g.addColorStop(.3,"rgba(82,239,255,.46)");g.addColorStop(1,"rgba(40,197,237,0)");ctx.fillStyle=g;ctx.fillRect(0,base-8,vw,50);for(let layer=0;layer<2;layer++){ctx.beginPath();for(let x=-20;x<=vw+20;x+=16){const y=base+layer*8+Math.sin(x*.027+state.time*(1.7-layer*.35)+layer*2.1)*(5-layer*2);x===-20?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.strokeStyle=layer?"rgba(159,250,255,.38)":"rgba(248,255,255,.94)";ctx.lineWidth=layer?2:4;ctx.stroke()}}
  function drawCaustics(){
    ctx.save();ctx.globalCompositeOperation="screen";
    for(let i=0;i<18;i++){
      const lane=i%6,row=Math.floor(i/6),rawX=(lane/5)*vw+state.time*(13+row*5)-state.camera.x*.035+i*47;
      const x=(rawX%(vw+180))-90,y=vh*(.18+row*.19)+Math.sin(state.time*.8+i*1.7)*22;
      ctx.strokeStyle=i%5===0?"rgba(177,255,85,.13)":"rgba(210,255,255,.19)";ctx.lineWidth=2+(i%3);ctx.shadowColor="#5fffff";ctx.shadowBlur=7;ctx.beginPath();ctx.ellipse(x,y,42+(i%4)*18,7+(i%2)*3,Math.sin(state.time*.23+i)*.28,0,TAU);ctx.stroke();
    }
    ctx.restore();
  }
  function drawOcean(){ctx.setTransform(dpr,0,0,dpr,0,0);const palettes=[[[115,255,255],[0,225,237],[0,48,112]],[[82,255,245],[0,219,216],[0,45,107]],[[55,250,255],[0,194,229],[6,39,116]],[[86,255,240],[0,211,207],[0,35,103]],[[139,255,255],[0,230,248],[12,27,100]]],p=palettes[(state.level-1)%palettes.length],rgb=c=>`rgb(${c.join(",")})`,sea=ctx.createLinearGradient(0,0,0,vh);sea.addColorStop(0,rgb(p[0]));sea.addColorStop(.34,rgb(p[1]));sea.addColorStop(1,rgb(p[2]));ctx.fillStyle=sea;ctx.fillRect(0,0,vw,vh);if(water.complete&&water.naturalWidth){ctx.save();try{if(!state.pattern)state.pattern=ctx.createPattern(water,"repeat");if(state.pattern){ctx.translate(-((state.camera.x*.18)%512),0);ctx.globalAlpha=.58;ctx.globalCompositeOperation="soft-light";ctx.fillStyle=state.pattern;ctx.fillRect(-512,-512,vw+1024,vh+1024)}}catch(_error){state.pattern=null}finally{ctx.restore()}}const g=ctx.createRadialGradient(vw*.38,vh*.24,20,vw*.5,vh*.5,Math.max(vw,vh)*.78);g.addColorStop(0,"rgba(210,255,255,.38)");g.addColorStop(.43,"rgba(0,255,232,.12)");g.addColorStop(1,"rgba(0,10,75,.52)");ctx.fillStyle=g;ctx.fillRect(0,0,vw,vh);drawCaustics();drawSky();drawSurface()}
  const screen=(x,y)=>({x:x-state.camera.x+vw/2,y:y-state.camera.y+vh/2});function visible(x,y,m=100){const p=screen(x,y);return p.x>-m&&p.x<vw+m&&p.y>-m&&p.y<vh+m}
  function drawSeabed(){const floorY=vh*.82,g=ctx.createLinearGradient(0,floorY,0,vh);g.addColorStop(0,"#ff3bd4");g.addColorStop(.19,"#6d28ff");g.addColorStop(.55,"#082d8f");g.addColorStop(1,"#02082d");ctx.beginPath();ctx.moveTo(0,vh);ctx.lineTo(0,floorY);for(let x=0;x<=vw+24;x+=24)ctx.lineTo(x,floorY+Math.sin((x+state.camera.x*.22)*.031)*7+Math.sin((x-state.camera.x*.13)*.073)*3);ctx.lineTo(vw,vh);ctx.closePath();ctx.fillStyle=g;ctx.fill();ctx.strokeStyle="rgba(0,245,255,.86)";ctx.shadowColor="#00f5ff";ctx.shadowBlur=12;ctx.lineWidth=3;ctx.stroke();ctx.shadowBlur=0;const shift=-((state.camera.x*.33)%82);for(let i=-1;i<Math.ceil(vw/82)+2;i++){const x=shift+i*82,y=floorY+18+(i%3)*13;ctx.fillStyle=i%2?"rgba(0,245,255,.3)":"rgba(157,255,0,.28)";ctx.beginPath();ctx.ellipse(x,y,13+(i%3)*4,7+(i%2)*3,-.18,0,TAU);ctx.fill()}}
  function drawObjectBubbles(o,p){if(o.kind==="treasure")return;ctx.save();ctx.strokeStyle="rgba(207,252,255,.72)";ctx.fillStyle="rgba(103,232,255,.12)";ctx.lineWidth=1.5;for(let i=0;i<3;i++){const rise=(state.time*(22+i*4)+o.phase*13+i*29)%88,x=p.x+Math.sin(state.time*2+i*2.4+o.phase)*9+(i-1)*5,y=p.y-o.size*.32-rise,r=2.2+i*1.2;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();ctx.stroke()}ctx.restore()}
  function drawDecor(){drawSeabed();for(const o of state.obstacles){if(!o.alive||!visible(o.x,o.y,110))continue;const p=screen(o.x,o.y),index=o.kind==="coral"?8:10,bob=o.kind==="treasure"?Math.sin(state.time*2.4+o.phase)*4:0;if(o.kind==="treasure"){const glow=ctx.createRadialGradient(p.x,p.y,4,p.x,p.y,o.size*.9);glow.addColorStop(0,"rgba(255,238,91,.38)");glow.addColorStop(1,"rgba(255,184,38,0)");ctx.fillStyle=glow;ctx.beginPath();ctx.arc(p.x,p.y,o.size*.9,0,TAU);ctx.fill()}if(o.kind==="shell")drawShellGraphic(p.x,p.y,o.size);else atlasCell(index,p.x,p.y+bob,o.size*1.32,o.size);drawObjectBubbles(o,p)}}
  function imageSprite(img,x,y,w,h,flip=false){if(!img.complete||!img.naturalWidth)return false;ctx.save();try{ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.drawImage(img,-w/2,-h/2,w,h);return true}catch(_error){return false}finally{ctx.restore()}}
  function drawCreature(f){if(!visible(f.x,f.y,f.size*2))return;const p=screen(f.x,f.y),flip=Math.cos(f.heading)<0;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(f.kind==="flyer"?f.flightTilt:Math.sin(f.phase)*.035);if(f.kind!=="flyer")ctx.translate(0,Math.sin(f.phase*.7)*3);let ratio=1.45,h=f.size*1.6;ctx.scale(1,1+Math.sin(f.phase*1.8)*.022);if(f.kind==="shark"){ratio=2.05;drawSharkGraphic(h,flip,f.phase)}else if(f.kind==="piranha"){ratio=1.62;drawPiranhaGraphic(h,flip,f.phase)}else if(f.kind==="lionfish"){ratio=1.58;drawLionfishGraphic(h,flip,f.phase)}else if(f.kind==="flyer"){ratio=1.72;drawFlyingFishGraphic(h,flip,f.phase)}else if(f.kind==="small"){ratio=1.45;drawSmallFishGraphic(h,flip,f.phase)}else{ratio=.8;atlasCell(f.phase%TAU>Math.PI?5:6,0,0,h*ratio,h,flip)}if(canEat(f)&&f.kind!=="small"){ctx.strokeStyle="rgba(113,255,174,.72)";ctx.shadowColor="#5dffae";ctx.shadowBlur=8;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,0,h*ratio*.55,h*.5,0,0,TAU);ctx.stroke();ctx.shadowBlur=0}ctx.restore()}
  function drawPlayer(){const p=state.player,s=screen(p.x,p.y);ctx.save();ctx.translate(s.x,s.y);ctx.rotate(p.angle);const h=p.size*2.15,phase=state.time*11;ctx.fillStyle="rgba(0,3,35,.3)";ctx.beginPath();ctx.ellipse(5,p.size*.48,p.size*1.05,p.size*.35,0,0,TAU);ctx.fill();ctx.strokeStyle="rgba(157,255,0,.9)";ctx.shadowColor="#00f5ff";ctx.shadowBlur=12;ctx.lineWidth=2.2;ctx.beginPath();ctx.ellipse(0,p.size*.5,p.size*1.12,p.size*.42,0,0,TAU);ctx.stroke();ctx.shadowBlur=0;ctx.scale(1,1+Math.sin(phase)*.022);fins(h,phase*.7,false,"#9dff00");vectorCell(2,0,0,h*1.43,h,false);imageSprite(finzoClosed,0,0,h*1.68,h,false);fishPolish("player",h,1.68,false,phase);if(p.bite>0)drawBiteMouth(h,p.bite/.28);ctx.restore()}
  function drawParticles(){for(const p of state.particles){const s=screen(p.x,p.y);ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(s.x,s.y,p.size,0,TAU);ctx.fill()}ctx.globalAlpha=1}
  function draw(){drawOcean();drawDecor();for(const f of state.creatures.filter(f=>f.alive).sort((a,b)=>a.y-b.y))drawCreature(f);drawPlayer();drawParticles();ctx.fillStyle="rgba(209,251,255,.24)";for(let i=0;i<19;i++){const x=(i*173+state.time*(14+i%3)-state.camera.x*.08)%(vw+50)-25,rawY=(i*97-state.time*(30+i%4))%(vh+80),y=rawY<0?rawY+vh+80:rawY;if(y<=waterline()+9)continue;ctx.beginPath();ctx.arc(x,y,1.5+i%3,0,TAU);ctx.fill()}}
  function loop(now,token){if(token!==state.loopToken||!state.running||state.paused)return;const dt=Math.min(.033,Math.max(.001,(now-state.last)/1000));state.last=now;update(dt);draw();if(state.running&&!state.paused&&token===state.loopToken)requestAnimationFrame(t=>loop(t,token))}
  function pause(){if(!state.running)return;state.paused=true;input.keys.clear();input.touches.clear();resetStick();show(ui.pause,true);ui.mobile.classList.remove("active")}
  function resume(){if(!state.running)return;state.paused=false;show(ui.pause,false);ui.mobile.classList.toggle("active",coarse);state.last=performance.now();const token=state.loopToken;requestAnimationFrame(t=>loop(t,token))}
  function resetStick(){input.stick.x=0;input.stick.y=0;input.stick.pointerId=null;ui.joystick.style.setProperty("--stick-x","0px");ui.joystick.style.setProperty("--stick-y","0px");ui.joystick.classList.remove("active")}
  function menu(){state.running=false;state.paused=false;state.loopToken++;input.keys.clear();input.touches.clear();resetStick();show(ui.menu,true);show(ui.over,false);show(ui.pause,false);show(ui.clear,false);show(ui.hud,false);ui.mobile.classList.remove("active");drawOcean()}
  const stopPageGesture=e=>{if(e.cancelable)e.preventDefault()};
  ["gesturestart","gesturechange","gestureend"].forEach(type=>document.addEventListener(type,stopPageGesture,{passive:false}));
  document.addEventListener("touchmove",stopPageGesture,{passive:false});
  document.addEventListener("dblclick",stopPageGesture,{passive:false});
  let lastTouchEnd=0;document.addEventListener("touchend",e=>{const now=Date.now();if(now-lastTouchEnd<360&&e.cancelable)e.preventDefault();lastTouchEnd=now},{passive:false});
  addEventListener("resize",resize,{passive:true});addEventListener("keydown",e=>{const key=e.key.length===1?e.key.toLowerCase():e.key;if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown","w","a","s","d"].includes(key)){e.preventDefault();input.keys.add(key)}if(key==="Escape"&&state.running)(state.paused?resume:pause)()});addEventListener("keyup",e=>{const key=e.key.length===1?e.key.toLowerCase():e.key;input.keys.delete(key)});addEventListener("blur",()=>{input.keys.clear();resetStick();if(!coarse&&state.running&&!state.paused)pause()});document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.running&&!state.paused)pause()});
  document.querySelectorAll("[data-dir]").forEach(btn=>{const release=e=>{input.touches.delete(e.pointerId);btn.classList.remove("active")};btn.addEventListener("pointerdown",e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);input.touches.set(e.pointerId,btn.dataset.dir);btn.classList.add("active")});btn.addEventListener("pointerup",release);btn.addEventListener("pointercancel",release);btn.addEventListener("lostpointercapture",release)});
  const moveStick=e=>{if(e.pointerId!==input.stick.pointerId)return;const r=ui.joystick.getBoundingClientRect(),radius=r.width*.34,dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),length=Math.hypot(dx,dy)||1,scale=Math.min(1,radius/length),sx=dx*scale,sy=dy*scale,nx=sx/radius,ny=sy/radius,response=v=>Math.sign(v)*Math.sqrt(Math.abs(v));input.stick.x=response(nx);input.stick.y=response(ny);ui.joystick.style.setProperty("--stick-x",sx+"px");ui.joystick.style.setProperty("--stick-y",sy+"px")};
  ui.joystick.addEventListener("pointerdown",e=>{e.preventDefault();input.stick.pointerId=e.pointerId;ui.joystick.setPointerCapture(e.pointerId);ui.joystick.classList.add("active");moveStick(e)});ui.joystick.addEventListener("pointermove",moveStick);ui.joystick.addEventListener("pointerrawupdate",moveStick);ui.joystick.addEventListener("pointerup",resetStick);ui.joystick.addEventListener("pointercancel",resetStick);ui.joystick.addEventListener("lostpointercapture",resetStick);
  ui.play.addEventListener("click",start);ui.again.addEventListener("click",()=>beginLevel());ui.home.addEventListener("click",menu);ui.pauseBtn.addEventListener("click",pause);ui.resume.addEventListener("click",resume);ui.quit.addEventListener("click",menu);ui.next.addEventListener("click",nextLevel);
  if(new URLSearchParams(location.search).has("test"))window.__PIRANHA3_DIAGNOSTICS__=()=>({running:state.running,paused:state.paused,campaignWon:state.campaignWon,level:state.level,score:state.score,player:state.player?{x:state.player.x,y:state.player.y,size:state.player.size,bite:state.player.bite}:null,keys:[...input.keys],touches:[...input.touches.values()],stick:{x:input.stick.x,y:input.stick.y}});
  resize();water.addEventListener("load",()=>{state.pattern=null;drawOcean()});drawOcean();
})();
