(()=>{
  "use strict";
  const TAU=Math.PI*2,canvas=document.querySelector("#game"),ctx=canvas.getContext("2d",{alpha:false});
  const atlas=new Image(),water=new Image(),finzoClosed=new Image(),finzoOpen=new Image(),sharkSprite=new Image();
  atlas.src="assets/ocean-atlas.png";water.src="assets/ocean-water.png";finzoClosed.src="assets/finzo-closed.png";finzoOpen.src="assets/finzo-open.png";sharkSprite.src="assets/shark.png";
  const $=s=>document.querySelector(s);
  const ui={menu:$("#menu"),hud:$("#hud"),over:$("#gameover"),pause:$("#pause"),clear:$("#level-clear"),play:$("#play-btn"),again:$("#again-btn"),home:$("#home-btn"),pauseBtn:$("#pause-btn"),resume:$("#resume-btn"),quit:$("#quit-btn"),next:$("#next-btn"),score:$("#score"),size:$("#size"),level:$("#level"),growth:$("#growth-fill"),growthLabel:$("#growth-label"),finalScore:$("#final-score"),finalSize:$("#final-size"),endTitle:$("#end-title"),clearEyebrow:$("#clear-eyebrow"),clearTitle:$("#clear-title"),clearCopy:$("#clear-copy"),message:$("#message"),mobile:$("#mobile-controls"),joystick:$("#joystick")};
  const input={keys:new Set(),touches:new Map(),stick:{x:0,y:0,pointerId:null}};
  const state={running:false,paused:false,campaignWon:false,last:0,time:0,score:0,totalScore:0,eaten:0,level:1,camera:{x:0,y:0},player:null,creatures:[],obstacles:[],particles:[],pattern:null,messageTimer:0,loopToken:0,winSize:108};
  let vw=innerWidth,vh=innerHeight,dpr=1,audio=null;
  const coarse=matchMedia("(pointer: coarse)").matches||/(?:^|[?&])mobile=1/.test(location.search);
  const best={score:Number(localStorage.getItem("piranha3-score")||0),level:Number(localStorage.getItem("piranha3-level")||1)};
  const show=(node,on)=>node.classList.toggle("active",on),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),random=(a,b)=>a+Math.random()*(b-a);
  function overlap(a,b,arx,ary,brx,bry){const dx=(a.x-b.x)/Math.max(1,arx+brx),dy=(a.y-b.y)/Math.max(1,ary+bry);return dx*dx+dy*dy<1}
  function resize(){vw=innerWidth;vh=innerHeight;dpr=Math.min(devicePixelRatio||1,coarse?1.25:1.7);canvas.width=Math.round(vw*dpr);canvas.height=Math.round(vh*dpr);canvas.style.width=vw+"px";canvas.style.height=vh+"px";ctx.setTransform(dpr,0,0,dpr,0,0);state.pattern=null;state.winSize=clamp(Math.min(vw*.28,vh*.31),96,126)}
  function safeTop(){return coarse?clamp(vh*.13,72,110):72}
  function initAudio(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume()}
  function sound(kind){if(!audio)return;const now=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);if(kind==="bite"){o.type="square";o.frequency.setValueAtTime(270,now);o.frequency.exponentialRampToValueAtTime(670,now+.08)}else if(kind==="grow"||kind==="win"){o.type="triangle";o.frequency.setValueAtTime(240,now);o.frequency.exponentialRampToValueAtTime(kind==="win"?1180:850,now+(kind==="win"?.5:.18))}else{o.type="sawtooth";o.frequency.setValueAtTime(145,now);o.frequency.exponentialRampToValueAtTime(38,now+.48)}g.gain.setValueAtTime(kind==="death"?.14:.075,now);g.gain.exponentialRampToValueAtTime(.001,now+(kind==="win"?.55:kind==="death"?.5:.16));o.start(now);o.stop(now+(kind==="win"?.58:kind==="death"?.52:.18))}
  function announce(text){ui.message.textContent=text;ui.message.classList.add("show");state.messageTimer=1.15}
  function difficulty(){return 1+(state.level-1)*.12+Math.min(.5,state.time/115)}
  function creatureTarget(){return Math.min(coarse?18:25,(coarse?8:11)+state.level+Math.floor(state.time/13))}
  function obstacleTarget(){return Math.min(coarse?6:8,3+Math.floor(state.time/28)+Math.floor(state.level/3))}
  function makeCreature(initial=false,forced=null){const roll=Math.random(),early=state.time<11,smallChance=clamp((early?.91:.8)-state.time*.0035-(state.level-1)*.045,.43,.91);let kind=forced;if(!kind){if(roll<smallChance)kind="small";else{const r=(roll-smallChance)/(1-smallChance);kind=r<.34?"piranha":r<.6?"shark":r<.8?"lionfish":"jelly"}}const scale=1+(state.level-1)*.055;const size=(kind==="small"?random(12,24):kind==="piranha"?random(31,44):kind==="shark"?random(53,73):kind==="lionfish"?random(37,50):random(28,41))*scale;const x=initial?state.camera.x+random(vw*.36,vw*1.75):state.camera.x+vw*.62+random(100,380),top=-vh/2+safeTop()+size*.55,y=random(kind==="jelly"?Math.max(0,top):top,vh*.34);return{kind,x,y,size,heading:Math.PI,speed:(kind==="small"?random(78,120):kind==="shark"?random(118,160):random(96,142))*difficulty(),phase:random(0,TAU),alive:true}}
  function makeObstacle(initial=false){const r=Math.random(),kind=r<.43?"coral":r<.75?"shell":"treasure";return{kind,x:initial?state.camera.x+random(vw*.4,vw*2.1):state.camera.x+vw*.62+random(170,540),y:vh*.36,size:kind==="coral"?random(54,77):kind==="shell"?random(42,60):random(47,63),phase:random(0,TAU),alive:true}}
  function resetLevel(){state.time=0;state.score=0;state.eaten=0;state.messageTimer=0;state.player={x:-vw*.2,y:0,size:30+Math.min(8,(state.level-1)*1.5),angle:0,bite:0,alive:true};state.camera.x=0;state.camera.y=0;state.creatures.length=0;state.obstacles.length=0;state.particles.length=0;for(let i=0;i<creatureTarget();i++)state.creatures.push(makeCreature(true,"small"));["treasure","coral","shell"].forEach((kind,i)=>{const o=makeObstacle(true);o.kind=kind;o.x=vw*(.82+i*.61);state.obstacles.push(o)});updateHud()}
  function beginLevel(){resetLevel();input.keys.clear();input.touches.clear();resetStick();state.running=true;state.paused=false;state.last=performance.now();state.loopToken++;show(ui.menu,false);show(ui.over,false);show(ui.pause,false);show(ui.clear,false);show(ui.hud,true);ui.hud.setAttribute("aria-hidden","false");ui.mobile.classList.toggle("active",coarse);ui.mobile.setAttribute("aria-hidden",String(!coarse));const token=state.loopToken;requestAnimationFrame(t=>loop(t,token));announce("OCEAN "+state.level+" — EAT WHAT IS SMALLER")}
  function start(){initAudio();state.level=1;state.totalScore=0;state.campaignWon=false;beginLevel()}
  function finish(reason){if(!state.running)return;state.running=false;state.loopToken++;state.player.alive=false;sound("death");burst(state.player.x,state.player.y,"#00f5ff",30);best.score=Math.max(best.score,state.totalScore+state.score);localStorage.setItem("piranha3-score",String(best.score));const titles={jelly:"POISONED BY A JELLYFISH!",shark:"THE SHARK WAS BIGGER",piranha:"PIRANHA ATTACK!",lionfish:"VENOMOUS LIONFISH!",coral:"CRASHED INTO CORAL",shell:"A SHELL STOPPED FINZO"};ui.endTitle.textContent=titles[reason]||"YOU WERE EATEN";ui.finalScore.textContent=(state.totalScore+state.score).toLocaleString("en-US");ui.finalSize.textContent=`Final size: ${(state.player.size/30).toFixed(1)}× · ${state.eaten} fish eaten`;show(ui.over,true);show(ui.hud,false);ui.mobile.classList.remove("active")}
  function winLevel(){if(!state.running)return;state.running=false;state.loopToken++;state.totalScore+=state.score;state.campaignWon=state.level>=5;best.level=Math.max(best.level,Math.min(5,state.level+1));best.score=Math.max(best.score,state.totalScore);localStorage.setItem("piranha3-level",String(best.level));localStorage.setItem("piranha3-score",String(best.score));sound("win");burst(state.player.x,state.player.y,"#9dff00",52);draw();if(state.campaignWon){ui.clearEyebrow.textContent="ULTIMATE OCEAN LEGEND";ui.clearTitle.textContent="ALL FIVE OCEANS CONQUERED!";ui.clearCopy.textContent="Finzo has become the brightest apex creature in the fluorescent deep. You won Piranha 3!";ui.next.textContent="PLAY AGAIN"}else{ui.clearEyebrow.textContent="APEX OF THE OCEAN";ui.clearTitle.textContent="OCEAN "+state.level+" CONQUERED!";ui.clearCopy.textContent="Finzo now enters a brighter, faster and more dangerous ocean.";ui.next.textContent="ENTER OCEAN "+(state.level+1)}show(ui.clear,true);show(ui.hud,false);ui.mobile.classList.remove("active")}
  function nextLevel(){if(state.campaignWon){state.level=1;state.totalScore=0;state.campaignWon=false}else state.level++;beginLevel()}
  function movement(){let x=input.stick.x,y=input.stick.y;for(const k of input.keys){if(k==="ArrowLeft"||k==="a")x--;if(k==="ArrowRight"||k==="d")x++;if(k==="ArrowUp"||k==="w")y--;if(k==="ArrowDown"||k==="s")y++}for(const d of input.touches.values()){if(d==="left")x--;if(d==="right")x++;if(d==="up")y--;if(d==="down")y++}const l=Math.hypot(x,y);return l>1?{x:x/l,y:y/l}:{x,y}}
  function canEat(fish){return fish.kind!=="jelly"&&state.player.size>fish.size*1.18}
  function update(dt){state.time+=dt;const p=state.player,m=movement(),scroll=Math.min(285,126+state.time*1.1+(state.level-1)*14);state.camera.x+=scroll*dt;p.x+=(scroll+m.x*235)*dt;p.y+=m.y*380*dt;p.x=clamp(p.x,state.camera.x-vw*.37,state.camera.x+vw*.23);p.y=clamp(p.y,-vh/2+safeTop()+p.size*.56,vh*.35);p.angle+=(m.y*.21-p.angle)*Math.min(1,dt*30);p.bite=Math.max(0,p.bite-dt);
    for(const f of state.creatures){f.phase+=dt*(f.kind==="jelly"?2.2:5);if(f.kind==="jelly"){f.x-=f.speed*.28*dt;f.y+=Math.sin(f.phase)*10*dt}else{f.x-=f.speed*dt;f.y+=Math.sin(f.phase*.55)*5*dt}if(overlap(p,f,p.size*.58,p.size*.3,f.size*.57,f.size*.28)){if(canEat(f))eat(f);else{finish(f.kind);return}}}
    for(const o of state.obstacles){if(!o.alive)continue;const treasure=o.kind==="treasure",touch=overlap(p,o,p.size*.55,p.size*.31,o.size*(treasure?.42:.36),o.size*(treasure?.34:.32));if(touch){if(treasure)collect(o);else{finish(o.kind);return}}}
    if(p.size>=state.winSize){winLevel();return}state.creatures=state.creatures.filter(f=>f.alive&&f.x>state.camera.x-vw*.72);state.obstacles=state.obstacles.filter(o=>o.alive&&o.x>state.camera.x-vw*.72);while(state.creatures.length<creatureTarget())state.creatures.push(makeCreature());while(state.obstacles.length<obstacleTarget())state.obstacles.push(makeObstacle());updateParticles(dt);if(state.messageTimer>0&&(state.messageTimer-=dt)<=0)ui.message.classList.remove("show");updateHud()}
  function eat(f){f.alive=false;state.eaten++;const hostile=f.kind!=="small",gain=Math.round(f.size*(hostile?2.4:1));state.score+=gain;const before=state.player.size;state.player.size=Math.min(state.winSize+4,state.player.size+(hostile?2.5:1.05)+f.size*(hostile?.075:.035));state.player.bite=.28;sound("bite");burst(f.x,f.y,hostile?"#ff2bd6":"#fff200",hostile?19:11);if(hostile)announce("FINZO ATE A "+f.kind.toUpperCase()+"!");else if(Math.floor(before/18)<Math.floor(state.player.size/18)){sound("grow");announce("FINZO GREW BIGGER!")}}
  function collect(o){o.alive=false;state.score+=85;state.player.size=Math.min(state.winSize+4,state.player.size+4.7);state.player.bite=.25;sound("grow");burst(o.x,o.y,"#ffe45d",17);announce("TREASURE — EXTRA GROWTH!")}
  function burst(x,y,color,count){for(let i=0;i<count;i++){const a=random(0,TAU),s=random(35,155);state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:random(.25,.68),max:.68,color,size:random(2,6)})}}
  function updateParticles(dt){for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.08,dt);p.vy*=Math.pow(.08,dt);p.life-=dt}state.particles=state.particles.filter(p=>p.life>0)}
  function updateHud(){const progress=clamp((state.player.size-30)/(state.winSize-30),0,1);ui.score.textContent=(state.totalScore+state.score).toLocaleString("en-US");ui.size.textContent=(state.player.size/30).toFixed(1)+"×";ui.level.textContent=state.level;ui.growth.style.width=Math.round(progress*100)+"%";ui.growthLabel.textContent=Math.round(progress*100)+"% TO DOMINANCE"}
  function vectorCell(index,x,y,w,h,flip=false,alpha=1){ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.globalAlpha=alpha;const body=(fill,stroke="#02072c")=>{ctx.fillStyle=fill;ctx.strokeStyle=stroke;ctx.lineWidth=Math.max(2,h*.045);ctx.beginPath();ctx.ellipse(0,0,w*.31,h*.34,0,0,TAU);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(-w*.27,0);ctx.lineTo(-w*.48,-h*.3);ctx.lineTo(-w*.46,h*.3);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(w*.19,-h*.09,h*.075,0,TAU);ctx.fill();ctx.fillStyle="#071a31";ctx.beginPath();ctx.arc(w*.21,-h*.09,h*.035,0,TAU);ctx.fill()};if(index<=4||index===7){const colors=["#00f5ff","#fff200","#0077ff","#ff2bd6","#00a6ff","#ff4b00","#a338ff","#ff315f"];body(colors[index]||"#00f5ff");if(index===3){ctx.fillStyle="#fff";for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(w*(.08+i*.045),h*.08);ctx.lineTo(w*(.105+i*.045),h*.2);ctx.lineTo(w*(.13+i*.045),h*.08);ctx.fill()}}if(index===4){ctx.fillStyle="#e8f7ff";ctx.beginPath();ctx.moveTo(-w*.08,0);ctx.lineTo(w*.31,h*.28);ctx.lineTo(w*.28,h*.05);ctx.closePath();ctx.fill()}if(index===7){ctx.strokeStyle="#fff200";ctx.lineWidth=2;for(let i=-3;i<=3;i++){ctx.beginPath();ctx.moveTo(-w*.08,i*h*.065);ctx.lineTo(-w*.34,i*h*.12);ctx.stroke()}}}else if(index===5||index===6){ctx.fillStyle=index===5?"#ff2bd6":"#8b2bff";ctx.strokeStyle="#dffbff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-h*.12,w*.25,Math.PI,TAU);ctx.lineTo(w*.25,h*.06);ctx.lineTo(-w*.25,h*.06);ctx.closePath();ctx.fill();ctx.stroke();for(let i=-2;i<=2;i++){ctx.beginPath();ctx.moveTo(i*w*.09,h*.04);ctx.quadraticCurveTo(i*w*.1+Math.sin(state.time*5+i)*8,h*.25,i*w*.08,h*.43);ctx.stroke()}}else if(index===8){ctx.strokeStyle="#ff2bd6";ctx.lineWidth=w*.12;ctx.lineCap="round";for(let i=-2;i<=2;i++){ctx.beginPath();ctx.moveTo(i*w*.09,h*.42);ctx.quadraticCurveTo(i*w*.13,-h*.02,(i+(i%2?.4:-.35))*w*.1,-h*(.22+Math.abs(i)*.05));ctx.stroke()}}else if(index===9){ctx.fillStyle="#00f5ff";ctx.strokeStyle="#132169";ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,h*.08,w*.3,Math.PI,TAU);ctx.quadraticCurveTo(0,-h*.03,-w*.3,h*.08);ctx.fill();ctx.stroke();for(let i=-2;i<=2;i++){ctx.beginPath();ctx.moveTo(0,h*.04);ctx.lineTo(i*w*.12,-h*.16);ctx.stroke()}}else{ctx.fillStyle="#7e3f08";ctx.strokeStyle="#fff200";ctx.lineWidth=4;ctx.beginPath();ctx.rect(-w*.32,-h*.23,w*.64,h*.48);ctx.fill();ctx.stroke();ctx.fillStyle="#fff200";ctx.beginPath();ctx.arc(0,0,h*.08,0,TAU);ctx.fill()}ctx.restore()}
  function atlasCell(index,x,y,w,h,flip=false,alpha=1){vectorCell(index,x,y,w,h,flip,alpha);if(!atlas.complete||!atlas.naturalWidth)return false;const cw=atlas.naturalWidth/4,ch=atlas.naturalHeight/3;ctx.save();try{ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.globalAlpha=alpha;ctx.drawImage(atlas,index%4*cw,Math.floor(index/4)*ch,cw,ch,-w/2,-h/2,w,h);return true}catch(_error){return false}finally{ctx.restore()}}
  function fins(length,phase,flip,color){const beat=Math.sin(phase);ctx.save();if(flip)ctx.scale(-1,1);ctx.globalAlpha=.75;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(-length*.39,-length*.12);ctx.quadraticCurveTo(-length*.63,-length*(.34+beat*.1),-length*.7,beat*length*.14);ctx.quadraticCurveTo(-length*.63,length*(.34-beat*.1),-length*.39,length*.12);ctx.closePath();ctx.fill();ctx.globalAlpha=.52;ctx.beginPath();ctx.ellipse(-length*.03,length*.2,length*.22,length*.07,beat*.32,0,TAU);ctx.fill();ctx.restore()}
  function drawSurface(){const base=25+Math.sin(state.time*1.7)*2,g=ctx.createLinearGradient(0,0,0,base+42);g.addColorStop(0,"rgba(226,255,255,.86)");g.addColorStop(.3,"rgba(82,239,255,.42)");g.addColorStop(1,"rgba(40,197,237,0)");ctx.fillStyle=g;ctx.fillRect(0,0,vw,base+42);for(let layer=0;layer<2;layer++){ctx.beginPath();for(let x=-20;x<=vw+20;x+=16){const y=base+layer*8+Math.sin(x*.027+state.time*(1.7-layer*.35)+layer*2.1)*(5-layer*2);x===-20?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.strokeStyle=layer?"rgba(159,250,255,.33)":"rgba(238,255,255,.82)";ctx.lineWidth=layer?2:4;ctx.stroke()}}
  function drawOcean(){ctx.setTransform(dpr,0,0,dpr,0,0);const hue=(198+(state.level-1)*46)%360;ctx.fillStyle=`hsl(${hue} 100% ${clamp(42+(state.level-1)*2.5,42,54)}%)`;ctx.fillRect(0,0,vw,vh);if(water.complete&&water.naturalWidth){ctx.save();try{if(!state.pattern)state.pattern=ctx.createPattern(water,"repeat");if(state.pattern){ctx.translate(-((state.camera.x*.18)%512),0);ctx.globalAlpha=.82;ctx.filter="saturate(1.45) contrast(1.12)";ctx.fillStyle=state.pattern;ctx.fillRect(-512,-512,vw+1024,vh+1024)}}catch(_error){state.pattern=null}finally{ctx.restore()}}const g=ctx.createRadialGradient(vw*.42,vh*.31,20,vw*.5,vh*.5,Math.max(vw,vh)*.76);g.addColorStop(0,`hsla(${hue-24} 100% 72%/.28)`);g.addColorStop(.46,`hsla(${hue+38} 100% 48%/.12)`);g.addColorStop(1,"rgba(1,0,54,.58)");ctx.fillStyle=g;ctx.fillRect(0,0,vw,vh);drawSurface()}
  const screen=(x,y)=>({x:x-state.camera.x+vw/2,y:y-state.camera.y+vh/2});function visible(x,y,m=100){const p=screen(x,y);return p.x>-m&&p.x<vw+m&&p.y>-m&&p.y<vh+m}
  function drawSeabed(){const floorY=vh*.82,g=ctx.createLinearGradient(0,floorY,0,vh);g.addColorStop(0,"#ff3bd4");g.addColorStop(.19,"#6d28ff");g.addColorStop(.55,"#082d8f");g.addColorStop(1,"#02082d");ctx.beginPath();ctx.moveTo(0,vh);ctx.lineTo(0,floorY);for(let x=0;x<=vw+24;x+=24)ctx.lineTo(x,floorY+Math.sin((x+state.camera.x*.22)*.031)*7+Math.sin((x-state.camera.x*.13)*.073)*3);ctx.lineTo(vw,vh);ctx.closePath();ctx.fillStyle=g;ctx.fill();ctx.strokeStyle="rgba(0,245,255,.86)";ctx.shadowColor="#00f5ff";ctx.shadowBlur=12;ctx.lineWidth=3;ctx.stroke();ctx.shadowBlur=0;const shift=-((state.camera.x*.33)%82);for(let i=-1;i<Math.ceil(vw/82)+2;i++){const x=shift+i*82,y=floorY+18+(i%3)*13;ctx.fillStyle=i%2?"rgba(0,245,255,.3)":"rgba(157,255,0,.28)";ctx.beginPath();ctx.ellipse(x,y,13+(i%3)*4,7+(i%2)*3,-.18,0,TAU);ctx.fill()}}
  function drawObjectBubbles(o,p){if(o.kind==="treasure")return;ctx.save();ctx.strokeStyle="rgba(207,252,255,.72)";ctx.fillStyle="rgba(103,232,255,.12)";ctx.lineWidth=1.5;for(let i=0;i<3;i++){const rise=(state.time*(22+i*4)+o.phase*13+i*29)%88,x=p.x+Math.sin(state.time*2+i*2.4+o.phase)*9+(i-1)*5,y=p.y-o.size*.32-rise,r=2.2+i*1.2;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();ctx.stroke()}ctx.restore()}
  function drawDecor(){drawSeabed();for(const o of state.obstacles){if(!o.alive||!visible(o.x,o.y,110))continue;const p=screen(o.x,o.y),index=o.kind==="coral"?8:o.kind==="shell"?9:10,bob=o.kind==="treasure"?Math.sin(state.time*2.4+o.phase)*4:0;if(o.kind==="treasure"){const glow=ctx.createRadialGradient(p.x,p.y,4,p.x,p.y,o.size*.9);glow.addColorStop(0,"rgba(255,238,91,.38)");glow.addColorStop(1,"rgba(255,184,38,0)");ctx.fillStyle=glow;ctx.beginPath();ctx.arc(p.x,p.y,o.size*.9,0,TAU);ctx.fill()}atlasCell(index,p.x,p.y+bob,o.size*1.32,o.size);drawObjectBubbles(o,p)}}
  function imageSprite(img,x,y,w,h,flip=false){if(!img.complete||!img.naturalWidth)return false;ctx.save();try{ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.drawImage(img,-w/2,-h/2,w,h);return true}catch(_error){return false}finally{ctx.restore()}}
  function drawCreature(f){if(!visible(f.x,f.y,f.size*2))return;const p=screen(f.x,f.y),flip=Math.cos(f.heading)<0;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.sin(f.phase)*.035);ctx.translate(0,Math.sin(f.phase*.7)*3);let ratio=1.45,h=f.size*1.6;if(f.kind==="shark"){ratio=1.9;ctx.scale(1,1+Math.sin(f.phase*1.8)*.02);vectorCell(4,0,0,h*1.75,h,true);imageSprite(sharkSprite,0,0,h*ratio,h,false)}else{let index;if(f.kind==="jelly"){index=f.phase%TAU>Math.PI?5:6;ratio=.8}else if(f.kind==="small"){index=f.size<18?0:1;ratio=1.42}else if(f.kind==="lionfish"){index=7}else index=3;if(f.kind!=="jelly"){ctx.rotate(flip?-f.heading+Math.PI:f.heading);fins(h,f.phase*1.8,flip,f.kind==="lionfish"?"#ff3e2e":f.kind==="piranha"?"#c837d7":"#f8d43b");ctx.scale(1,1+Math.sin(f.phase*1.8)*.026)}atlasCell(index,0,0,h*ratio,h,flip)}if(canEat(f)&&f.kind!=="small"){ctx.strokeStyle="rgba(113,255,174,.72)";ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,0,h*ratio*.55,h*.5,0,0,TAU);ctx.stroke()}ctx.restore()}
  function drawPlayer(){const p=state.player,s=screen(p.x,p.y);ctx.save();ctx.translate(s.x,s.y);ctx.rotate(p.angle);const h=p.size*2.15,phase=state.time*11;ctx.fillStyle="rgba(0,3,35,.3)";ctx.beginPath();ctx.ellipse(5,p.size*.48,p.size*1.05,p.size*.35,0,0,TAU);ctx.fill();ctx.strokeStyle="rgba(157,255,0,.9)";ctx.shadowColor="#00f5ff";ctx.shadowBlur=12;ctx.lineWidth=2.2;ctx.beginPath();ctx.ellipse(0,p.size*.5,p.size*1.12,p.size*.42,0,0,TAU);ctx.stroke();ctx.shadowBlur=0;ctx.scale(1,1+Math.sin(phase)*.022);const sprite=p.bite>0?finzoOpen:finzoClosed;vectorCell(2,0,0,h*1.43,h,false);imageSprite(sprite,0,0,h*1.68,h,false);ctx.restore()}
  function drawParticles(){for(const p of state.particles){const s=screen(p.x,p.y);ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(s.x,s.y,p.size,0,TAU);ctx.fill()}ctx.globalAlpha=1}
  function draw(){drawOcean();drawDecor();for(const f of state.creatures.filter(f=>f.alive).sort((a,b)=>a.y-b.y))drawCreature(f);drawPlayer();drawParticles();ctx.fillStyle="rgba(209,251,255,.24)";for(let i=0;i<19;i++){const x=(i*173+state.time*(14+i%3)-state.camera.x*.08)%(vw+50)-25,y=(i*97-state.time*(30+i%4))%(vh+80);ctx.beginPath();ctx.arc(x,y<0?y+vh+80:y,1.5+i%3,0,TAU);ctx.fill()}}
  function loop(now,token){if(token!==state.loopToken||!state.running||state.paused)return;const dt=Math.min(.033,Math.max(.001,(now-state.last)/1000));state.last=now;update(dt);draw();if(state.running&&!state.paused&&token===state.loopToken)requestAnimationFrame(t=>loop(t,token))}
  function pause(){if(!state.running)return;state.paused=true;input.keys.clear();input.touches.clear();resetStick();show(ui.pause,true);ui.mobile.classList.remove("active")}
  function resume(){if(!state.running)return;state.paused=false;show(ui.pause,false);ui.mobile.classList.toggle("active",coarse);state.last=performance.now();const token=state.loopToken;requestAnimationFrame(t=>loop(t,token))}
  function resetStick(){input.stick.x=0;input.stick.y=0;input.stick.pointerId=null;ui.joystick.style.setProperty("--stick-x","0px");ui.joystick.style.setProperty("--stick-y","0px");ui.joystick.classList.remove("active")}
  function menu(){state.running=false;state.paused=false;state.loopToken++;input.keys.clear();input.touches.clear();resetStick();show(ui.menu,true);show(ui.over,false);show(ui.pause,false);show(ui.clear,false);show(ui.hud,false);ui.mobile.classList.remove("active");drawOcean()}
  const stopPageGesture=e=>{if(e.cancelable)e.preventDefault()};
  ["gesturestart","gesturechange","gestureend"].forEach(type=>document.addEventListener(type,stopPageGesture,{passive:false}));
  document.addEventListener("touchmove",stopPageGesture,{passive:false});
  document.addEventListener("dblclick",stopPageGesture,{passive:false});
  let lastTouchEnd=0;document.addEventListener("touchend",e=>{const now=Date.now();if(now-lastTouchEnd<360&&e.cancelable)e.preventDefault();lastTouchEnd=now},{passive:false});
  addEventListener("resize",resize,{passive:true});addEventListener("keydown",e=>{if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown","w","a","s","d"].includes(e.key)){e.preventDefault();input.keys.add(e.key)}if(e.key==="Escape"&&state.running)(state.paused?resume:pause)()});addEventListener("keyup",e=>input.keys.delete(e.key));addEventListener("blur",()=>{input.keys.clear();resetStick();if(!coarse&&state.running&&!state.paused)pause()});document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.running&&!state.paused)pause()});
  document.querySelectorAll("[data-dir]").forEach(btn=>{const release=e=>{input.touches.delete(e.pointerId);btn.classList.remove("active")};btn.addEventListener("pointerdown",e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);input.touches.set(e.pointerId,btn.dataset.dir);btn.classList.add("active")});btn.addEventListener("pointerup",release);btn.addEventListener("pointercancel",release);btn.addEventListener("lostpointercapture",release)});
  const moveStick=e=>{if(e.pointerId!==input.stick.pointerId)return;const r=ui.joystick.getBoundingClientRect(),radius=r.width*.34,dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),length=Math.hypot(dx,dy)||1,scale=Math.min(1,radius/length),sx=dx*scale,sy=dy*scale;input.stick.x=sx/radius;input.stick.y=sy/radius;ui.joystick.style.setProperty("--stick-x",sx+"px");ui.joystick.style.setProperty("--stick-y",sy+"px")};
  ui.joystick.addEventListener("pointerdown",e=>{e.preventDefault();input.stick.pointerId=e.pointerId;ui.joystick.setPointerCapture(e.pointerId);ui.joystick.classList.add("active");moveStick(e)});ui.joystick.addEventListener("pointermove",moveStick);ui.joystick.addEventListener("pointerup",resetStick);ui.joystick.addEventListener("pointercancel",resetStick);ui.joystick.addEventListener("lostpointercapture",resetStick);
  ui.play.addEventListener("click",start);ui.again.addEventListener("click",()=>beginLevel());ui.home.addEventListener("click",menu);ui.pauseBtn.addEventListener("click",pause);ui.resume.addEventListener("click",resume);ui.quit.addEventListener("click",menu);ui.next.addEventListener("click",nextLevel);
  if(new URLSearchParams(location.search).has("test"))window.__PIRANHA3_DIAGNOSTICS__=()=>({running:state.running,paused:state.paused,campaignWon:state.campaignWon,level:state.level,score:state.score,player:state.player?{x:state.player.x,y:state.player.y,size:state.player.size,bite:state.player.bite}:null,keys:[...input.keys],touches:[...input.touches.values()],stick:{x:input.stick.x,y:input.stick.y}});
  resize();water.addEventListener("load",()=>{state.pattern=null;drawOcean()});drawOcean();
})();
