const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const R=require('../core.js');let checks=0;
function test(name,f){f();checks++;console.log('PASS',name);}
function clear(g){for(const p of [...g.pickups])R.collect(g,p);}
test('five finite boards with paired, spaced numbers',()=>{for(let level=1;level<=5;level++){const g=R.create('layout',level);assert.equal(g.pickups.length,R.COUNTS[level-1]);assert.equal(g.pickups.reduce((a,p)=>a+p.v,0),0);for(let i=0;i<g.pickups.length;i++)for(let j=i+1;j<g.pickups.length;j++)assert(Math.hypot(g.pickups[i].x-g.pickups[j].x,g.pickups[i].y-g.pickups[j].y)>=100);assert.deepEqual(g.pickups,R.create('layout',level).pickups);}});
test('numbers never respawn and the last one completes the level',()=>{const g=R.create('clear');const p=g.pickups[0];assert(R.collect(g,p));assert.equal(R.collect(g,p),false);assert.equal(g.pickups.length,5);clear(g);assert(g.ended&&g.won);assert(!g.campaignComplete);assert.equal(g.pickups.length,0);const score=g.score;R.step(g,.1);assert.equal(g.score,score);});
test('flips and nonzero final charge cannot block completion',()=>{const g=R.create('flip');R.collect(g,g.pickups[0]);R.flip(g);assert.equal(g.charge,1);clear(g);assert.notEqual(g.charge,0);assert(g.won);});
test('large charges are safe; arithmetic cannot remove shields',()=>{const g=R.create('safe',5);g.invulnerable=0;for(const p of [...g.pickups])if(p.v>0)R.collect(g,p);assert(g.charge>9);assert.equal(g.lives,3);clear(g);assert(g.won);});
test('no timer and no enemies in the first two levels',()=>{for(const level of [1,2]){const g=R.create('calm',level);for(let i=0;i<6001;i++)R.step(g,.1);assert(!g.ended);assert.equal(g.lives,3);assert.equal(g.spawned,0);assert.equal(g.pickups.length,g.total);}});
test('tap near a number arrives at its centre, collects once and stays still',()=>{const g=R.create('tap');const p=g.pickups[0];R.setTarget(g,p.x+20,p.y-13);for(let i=0;i<200;i++)R.step(g,1/60);assert.equal(g.x,p.x);assert.equal(g.y,p.y);assert.equal(g.target,null);assert.equal(g.collected,1);const x=g.x,y=g.y;for(let i=0;i<100;i++)R.step(g,1/60);assert.equal(g.x,x);assert.equal(g.y,y);});
test('keyboard cancels target; release stops without drift; diagonal speed matches',()=>{const a=R.create('move'),b=R.create('move');a.pickups=[];b.pickups=[];a.enemyQuota=b.enemyQuota=0;R.setTarget(a,600,100);const x=a.x,y=a.y;R.step(a,.1,{x:1});assert.equal(a.target,null);R.step(b,.1,{x:1,y:-1});assert(Math.abs(Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))<1e-8);const pos=a.x;R.step(a,.1,{});assert.equal(a.x,pos);assert.deepEqual(R.stickVector(.02,-.03),{x:0,y:0});});
test('five levels lead to final victory, refill shields and preserve scores',()=>{let g=R.create('campaign');for(let n=1;n<=5;n++){assert.equal(g.level,n);g.lives=1;clear(g);assert(g.won);const score=g.score;if(n<5){g=R.nextLevel(g);assert.equal(g.lives,3);assert.equal(g.score,score);assert.equal(g.collected,0);}}assert(g.campaignComplete);assert.equal(R.nextLevel(g),g);});
test('retry resets only current level and prevents score inflation',()=>{let g=R.create('retry');clear(g);g=R.nextLevel(g);const bank=g.score;R.collect(g,g.pickups[0]);const retry=R.retryLevel(g);assert.equal(retry.level,2);assert.equal(retry.score,bank);assert.equal(retry.collected,0);assert.equal(retry.lives,3);});
function drive(seed){let g=R.create(seed),trace=[];for(let level=1;level<=5;level++){let steps=0;while(!g.ended&&steps++<15000){if(!g.target&&g.pickups.length){const p=g.pickups[0];R.setTarget(g,p.x,p.y);}R.step(g,1/60);g.events=[];}assert(g.won,'Simple tap route failed: '+seed+' level '+level);trace.push({level:g.level,time:g.time,totalTime:g.totalTime,x:g.x,y:g.y,score:g.score,charge:g.charge,lives:g.lives,novas:g.novas,collected:g.collected,spawned:g.spawned});if(level<5)g=R.nextLevel(g);}return trace;}
test('simple tap routes finish all five levels for five seeds',()=>{for(const seed of ['2026-09-08','friend','cross-platform','R100','R200'])drive(seed);});
fs.writeFileSync(path.join(__dirname,'parity-expected.json'),JSON.stringify(drive('cross-platform'),null,2)+'\n');
console.log(checks+' core checks passed; five-level movement trace recorded.');
