// Runtime smoke through a mocked DOM/canvas API. This is not a browser playtest.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');const nodes=new Map();let draws=0,raf,time=1000;
const drawing=new Proxy({createRadialGradient:()=>({addColorStop(){}}),createLinearGradient:()=>({addColorStop(){}})},{get(o,k){if(k in o)return o[k];return()=>{draws++;};},set(o,k,v){o[k]=v;return true;}});
function node(id){return{id,textContent:'',innerHTML:'',value:'',disabled:false,hidden:false,tagName:id==='seed'?'INPUT':'DIV',style:{},listeners:{},firstChild:{textContent:''},span:{textContent:''},width:720,height:900,attrs:{},classList:{classes:new Set(),add(c){this.classes.add(c);},remove(c){this.classes.delete(c);}},addEventListener(n,f){this.listeners[n]=f;},querySelector(s){assert.equal(s,'span');return this.span;},setAttribute(k,v){this.attrs[k]=v;},focus(){},setPointerCapture(){},getContext(){return drawing;},getBoundingClientRect(){return{left:0,top:0,right:360,bottom:450,width:360,height:450};}};}
for(const m of html.matchAll(/id="([^"]+)"/g))nodes.set(m[1],node(m[1]));
const doc={getElementById(id){assert(nodes.has(id),'Unknown HTML id '+id);return nodes.get(id);},hidden:false,listeners:{},addEventListener(n,f){this.listeners[n]=f;}};
const R=require('../core.js'),api={...R};for(const name of ['create','nextLevel','retryLevel'])api[name]=(...args)=>{const g=R[name](...args);api.latest=g;return g;};
const sandbox={document:doc,ZeroRiot:api,URL,URLSearchParams,Math,Date,Number,String,Set,localStorage:{getItem:()=>null,setItem(){}},matchMedia:()=>({matches:false}),location:{href:'https://example.test/zero-riot/?seed=smoke',search:'?seed=smoke'},navigator:{clipboard:{async writeText(t){sandbox.copied=t;}}},requestAnimationFrame(f){raf=f;},listeners:{},addEventListener(n,f){this.listeners[n]=f;}};sandbox.window=sandbox;
vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../game.js'),'utf8'),sandbox);
function click(id){return nodes.get(id).listeners.click();}function tick(n=1){for(let i=0;i<n;i++){time+=1000/60;raf(time);}}function key(code){sandbox.listeners.keydown({code,target:{tagName:'CANVAS'},preventDefault(){}});}
tick(2);assert(draws>0);click('start');tick(2);assert.equal(api.latest.seed,'smoke');let g=api.latest;
const board=nodes.get('game');board.listeners.pointerdown({pointerId:9,pointerType:'touch',button:0,clientX:130,clientY:270,preventDefault(){}});assert.equal(g.angle,Math.atan2(260-360,802-540));assert.equal(g.shots,0);
board.listeners.pointercancel();board.listeners.pointerup({pointerId:9,clientX:130,clientY:270});assert.equal(g.shots,0);
click('hint');const angle=g.angle,x=(360+Math.sin(angle)*200)/2,y=(802-Math.cos(angle)*200)/2;board.listeners.pointerdown({pointerId:10,pointerType:'touch',button:0,clientX:x,clientY:y,preventDefault(){}});board.listeners.pointerup({pointerId:10,clientX:x,clientY:y});assert(g.projectile);tick(160);assert.equal(g.misses,0);assert(g.bubbles.length<g.initial);
board.listeners.pointerdown({pointerId:11,pointerType:'touch',button:0,clientX:180,clientY:100,preventDefault(){}});const shots=g.shots;board.listeners.pointerup({pointerId:11,clientX:400,clientY:100});assert.equal(g.shots,shots);
key('ArrowRight');tick(10);sandbox.listeners.keyup({code:'ArrowRight'});const a=g.angle;tick(10);assert.equal(g.angle,a);key('Digit3');assert.equal(g.selected,2);assert.equal(nodes.get('ammo2').attrs['aria-pressed'],'true');
click('pause');const t=g.time;tick(20);assert.equal(g.time,t);click('resume');tick(4);assert(g.time>t);
sandbox.listeners.blur();const t2=g.time;tick(10);assert.equal(g.time,t2);click('resume');
for(let level=1;level<=12;level++){g=api.latest;assert.equal(g.level,level);let guard=0;while(!g.ended&&guard++<100){click('hint');click('fire');tick(420);}assert(g.won);assert.equal(g.rescued,g.lumiTotal);assert.equal(nodes.get('board-wrap').attrs['data-world'],String(R.world(g)));assert.equal(nodes.get('rescue-count').textContent,`LUMIS ${g.lumiTotal} / ${g.lumiTotal}`);tick(80);assert.equal(nodes.get('remaining').textContent,0);assert.equal(nodes.get('results').hidden,false);if(level===12)assert.match(nodes.get('next').textContent,/PLAY AGAIN/);click('next');tick(3);}
assert.equal(api.latest.level,1);assert.equal(api.latest.score,0);
console.log('PASS web runtime: touch aim/release/cancel/outside, keyboard stop, ammo, pause/focus, all four operations, three worlds, Lumi counts, 12 level/result transitions and final replay. Canvas calls executed; no visual QA.');
