(()=>{
  "use strict";
  const TAU=Math.PI*2,canvas=document.querySelector("#game"),ctx=canvas.getContext("2d",{alpha:false});
  const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),dist2=(a,b)=>{const x=a.x-b.x,y=a.y-b.y;return x*x+y*y};
  const ui={menu:$("#menu"),hud:$("#hud"),upgrade:$("#upgrade"),pause:$("#pause"),over:$("#gameover"),victory:$("#victory"),play:$("#play-btn"),pauseBtn:$("#pause-btn"),resume:$("#resume-btn"),quit:$("#quit-btn"),again:$("#again-btn"),home:$("#home-btn"),victoryAgain:$("#victory-again"),victoryHome:$("#victory-home"),upgradeOptions:$("#upgrade-options"),hp:$("#hp"),hpFill:$("#hp-fill"),time:$("#time"),level:$("#level"),xpFill:$("#xp-fill"),xpLabel:$("#xp-label"),combo:$("#combo"),toast:$("#toast"),bossBar:$("#boss-bar"),bossFill:$("#boss-bar i"),finalScore:$("#final-score"),finalKills:$("#final-kills"),winScore:$("#win-score"),winCombo:$("#win-combo"),best:$("#best-score"),mobile:$("#mobile-controls"),stick:$("#stick"),dash:$("#dash")};
  const hunters={ion:{name:"ION",color:"#5ff8ff",accent:"#825cff",speed:250,fire:.43,damage:2.2,hp:100},pulse:{name:"PULSE",color:"#ff4fd8",accent:"#5ff8ff",speed:285,fire:.34,damage:1.75,hp:88},nova:{name:"NOVA",color:"#ffe66d",accent:"#ff604f",speed:225,fire:.51,damage:3.15,hp:116}};
  const input={keys:new Set(),stick:{x:0,y:0,id:null},last:{x:1,y:0}};
  const state={mode:"menu",hunter:"ion",time:0,remaining:120,last:0,score:0,kills:0,combo:1,maxCombo:1,comboTimer:0,level:1,xp:0,xpNeed:8,player:null,enemies:[],bullets:[],enemyBullets:[],shards:[],particles:[],spawnTimer:0,boss:null,bossSpawned:false,shake:0,toastTimer:0,ambient:0,shotTick:0,upgradeCounts:{},pendingLevels:0};
  let vw=innerWidth,vh=innerHeight,dpr=1,audio=null;
  const coarse=matchMedia("(pointer:coarse)").matches||new URLSearchParams(location.search).has("mobile");
  let best=Number(localStorage.getItem("rift-rush-best")||0);ui.best.textContent=best.toLocaleString("en-US");

  function show(el,on){el.classList.toggle("active",on)}
  function resize(){vw=innerWidth;vh=innerHeight;dpr=Math.min(devicePixelRatio||1,coarse?1.25:1.6);canvas.width=Math.round(vw*dpr);canvas.height=Math.round(vh*dpr);canvas.style.width=vw+"px";canvas.style.height=vh+"px";ctx.setTransform(dpr,0,0,dpr,0,0)}
  function initAudio(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume()}
  function tone(kind){if(!audio)return;const now=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);let duration=.1,volume=.035;o.type="square";if(kind==="dash"){o.type="sawtooth";o.frequency.setValueAtTime(170,now);o.frequency.exponentialRampToValueAtTime(720,now+.13);duration=.15;volume=.055}else if(kind==="hit"){o.frequency.setValueAtTime(105,now);o.frequency.exponentialRampToValueAtTime(48,now+.16);duration=.18;volume=.06}else if(kind==="kill"){o.type="triangle";o.frequency.setValueAtTime(300,now);o.frequency.exponentialRampToValueAtTime(610,now+.07);duration=.09}else if(kind==="level"){o.type="triangle";o.frequency.setValueAtTime(280,now);o.frequency.exponentialRampToValueAtTime(1080,now+.38);duration=.42;volume=.07}else if(kind==="boss"){o.type="sawtooth";o.frequency.setValueAtTime(72,now);o.frequency.exponentialRampToValueAtTime(34,now+.62);duration=.68;volume=.1}else if(kind==="win"){o.type="triangle";o.frequency.setValueAtTime(240,now);o.frequency.exponentialRampToValueAtTime(1320,now+.68);duration=.74;volume=.08}else{o.frequency.setValueAtTime(520,now);o.frequency.exponentialRampToValueAtTime(260,now+.055);volume=.018}g.gain.setValueAtTime(volume,now);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.start(now);o.stop(now+duration+.02)}
  function toast(text){ui.toast.textContent=text;ui.toast.classList.add("show");state.toastTimer=1.35}
  function setHunter(name){state.hunter=name;document.querySelectorAll(".hunter").forEach(b=>b.classList.toggle("active",b.dataset.hunter===name));const h=hunters[name];document.documentElement.style.setProperty("--cyan",h.color);document.documentElement.style.setProperty("--pink",h.accent)}
  function newPlayer(){const h=hunters[state.hunter];return{x:0,y:0,vx:0,vy:0,r:18,hp:h.hp,maxHp:h.hp,speed:h.speed,fireRate:h.fire,fireTimer:.1,damage:h.damage,projectiles:1,spread:.16,pierce:0,magnet:92,drones:0,dashCd:0,dashMax:1.75,dashT:0,dashX:1,dashY:0,invuln:0,angle:0,color:h.color,accent:h.accent}}
  function reset(){state.time=0;state.remaining=120;state.score=0;state.kills=0;state.combo=1;state.maxCombo=1;state.comboTimer=0;state.level=1;state.xp=0;state.xpNeed=8;state.player=newPlayer();state.enemies.length=0;state.bullets.length=0;state.enemyBullets.length=0;state.shards.length=0;state.particles.length=0;state.spawnTimer=.55;state.boss=null;state.bossSpawned=false;state.shake=0;state.toastTimer=0;state.upgradeCounts={};state.pendingLevels=0;input.keys.clear();resetStick();updateHud()}
  function start(){initAudio();reset();state.mode="playing";state.last=performance.now();show(ui.menu,false);show(ui.over,false);show(ui.victory,false);show(ui.pause,false);show(ui.upgrade,false);show(ui.hud,true);ui.hud.setAttribute("aria-hidden","false");ui.mobile.classList.toggle("active",coarse);ui.mobile.setAttribute("aria-hidden",String(!coarse));ui.bossBar.classList.remove("active");toast("SURVIVE 02:00 — AUTO-AIM ONLINE")}
  function menu(){state.mode="menu";input.keys.clear();resetStick();show(ui.menu,true);show(ui.over,false);show(ui.victory,false);show(ui.pause,false);show(ui.upgrade,false);show(ui.hud,false);ui.mobile.classList.remove("active");ui.bossBar.classList.remove("active")}
  function finish(win=false){if(state.mode!=="playing")return;state.mode=win?"victory":"gameover";input.keys.clear();resetStick();best=Math.max(best,Math.round(state.score));localStorage.setItem("rift-rush-best",String(best));ui.best.textContent=best.toLocaleString("en-US");show(ui.hud,false);ui.mobile.classList.remove("active");ui.bossBar.classList.remove("active");if(win){tone("win");burst(state.player.x,state.player.y,state.player.color,70,260);ui.winScore.textContent=Math.round(state.score).toLocaleString("en-US");ui.winCombo.textContent="x"+state.maxCombo;show(ui.victory,true)}else{tone("hit");burst(state.player.x,state.player.y,"#ff407c",42,220);ui.finalScore.textContent=Math.round(state.score).toLocaleString("en-US");ui.finalKills.textContent=state.kills;show(ui.over,true)}}
  function pause(){if(state.mode!=="playing")return;state.mode="paused";input.keys.clear();resetStick();show(ui.pause,true);ui.mobile.classList.remove("active")}
  function resume(){if(state.mode!=="paused")return;state.mode="playing";state.last=performance.now();show(ui.pause,false);ui.mobile.classList.toggle("active",coarse)}

  function moveVector(){let x=input.stick.x,y=input.stick.y;for(const k of input.keys){if(k==="ArrowLeft"||k==="a")x--;if(k==="ArrowRight"||k==="d")x++;if(k==="ArrowUp"||k==="w")y--;if(k==="ArrowDown"||k==="s")y++}const l=Math.hypot(x,y);if(l>.08){x/=Math.max(1,l);y/=Math.max(1,l);input.last.x=x;input.last.y=y}return{x,y}}
  function dash(){const p=state.player;if(state.mode!=="playing"||!p||p.dashCd>0)return;const m=moveVector(),l=Math.hypot(m.x,m.y);p.dashX=l>.05?m.x:input.last.x;p.dashY=l>.05?m.y:input.last.y;p.dashT=.17;p.dashCd=p.dashMax;p.invuln=.27;state.shake=5;tone("dash");burst(p.x-p.dashX*8,p.y-p.dashY*8,p.color,15,120)}
  function edgeSpawn(distance=0){const p=state.player,a=rand(0,TAU),radius=distance||Math.hypot(vw,vh)*.56+rand(70,190);return{x:p.x+Math.cos(a)*radius,y:p.y+Math.sin(a)*radius}}
  function spawnEnemy(forced){const progress=state.time/120,r=Math.random();let type=forced||"spark";if(!forced){if(progress>.63&&r>.79)type="wraith";else if(progress>.42&&r>.66)type="tank";else if(progress>.18&&r>.52)type="blade"}const pos=edgeSpawn(),scale=1+progress*.62+Math.max(0,state.level-1)*.025,base={spark:{r:11,hp:2.4,speed:96,score:12,color:"#5ff8ff"},blade:{r:16,hp:5.5,speed:77,score:25,color:"#ff4fd8"},tank:{r:24,hp:15,speed:47,score:62,color:"#ff9f43"},wraith:{r:17,hp:8,speed:58,score:48,color:"#9b74ff"}}[type];state.enemies.push({type,x:pos.x,y:pos.y,r:base.r,hp:base.hp*scale,maxHp:base.hp*scale,speed:base.speed*(1+progress*.2),score:base.score,color:base.color,phase:rand(0,TAU),hit:0,shoot:rand(.8,2.2),boss:false})}
  function spawnBoss(){if(state.bossSpawned)return;state.bossSpawned=true;const pos=edgeSpawn(Math.max(vw,vh)*.48);const hp=190+state.level*13;const b={type:"titan",x:pos.x,y:pos.y,r:54,hp,maxHp:hp,speed:33,score:2500,color:"#ff43d1",phase:0,hit:0,shoot:1.1,boss:true};state.enemies.push(b);state.boss=b;ui.bossBar.classList.add("active");tone("boss");toast("⚠ RIFT TITAN INBOUND ⚠");state.shake=14}
  function shoot(){const p=state.player;if(!state.enemies.length)return;let target=null,bestD=720*720;for(const e of state.enemies){const d=dist2(p,e);if(d<bestD){bestD=d;target=e}}if(!target)return;const base=Math.atan2(target.y-p.y,target.x-p.x),count=p.projectiles;for(let i=0;i<count;i++){const off=(i-(count-1)/2)*p.spread,a=base+off;state.bullets.push({x:p.x+Math.cos(a)*23,y:p.y+Math.sin(a)*23,vx:Math.cos(a)*600,vy:Math.sin(a)*600,r:5,life:1.25,damage:p.damage,pierce:p.pierce,color:p.color})}state.shotTick++;if(state.shotTick%3===0)tone("shoot")}
  function enemyShot(e){const p=state.player,a=Math.atan2(p.y-e.y,p.x-e.x),count=e.boss?10:1;for(let i=0;i<count;i++){const angle=e.boss?a+(i-(count-1)/2)*.18:a+rand(-.08,.08),speed=e.boss?190:235;state.enemyBullets.push({x:e.x+Math.cos(angle)*e.r,y:e.y+Math.sin(angle)*e.r,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,r:e.boss?7:5,life:e.boss?4.5:3.2,damage:e.boss?15:10,color:e.boss?"#ff3e8a":"#a875ff"})}}
  function hitPlayer(damage,source){const p=state.player;if(p.invuln>0||p.dashT>0)return;p.hp-=damage;p.invuln=.72;state.shake=10;state.combo=1;state.comboTimer=0;tone("hit");burst(p.x,p.y,"#ff437d",19,170);if(source){const a=Math.atan2(p.y-source.y,p.x-source.x);p.x+=Math.cos(a)*18;p.y+=Math.sin(a)*18}if(p.hp<=0){p.hp=0;updateHud();finish(false)}}
  function kill(e){e.dead=true;state.kills++;if(state.comboTimer>0)state.combo=Math.min(99,state.combo+1);else state.combo=1;state.comboTimer=2.25;state.maxCombo=Math.max(state.maxCombo,state.combo);state.score+=e.score*(1+Math.min(9,state.combo-1)*.09);const drops=e.boss?24:e.type==="tank"?4:e.type==="wraith"?3:e.type==="blade"?2:1;for(let i=0;i<drops;i++)state.shards.push({x:e.x+rand(-e.r,e.r),y:e.y+rand(-e.r,e.r),vx:rand(-55,55),vy:rand(-55,55),r:e.boss?6:4,value:e.boss?2:1,phase:rand(0,TAU)});burst(e.x,e.y,e.color,e.boss?80:14,e.boss?290:145);tone(e.boss?"boss":"kill");if(e.boss){state.boss=null;ui.bossBar.classList.remove("active");finish(true)}}
  function gainShard(s){s.dead=true;state.xp+=s.value;state.score+=3*s.value;burst(s.x,s.y,state.player.color,3,50);while(state.xp>=state.xpNeed){state.xp-=state.xpNeed;state.level++;state.xpNeed=Math.round(7+state.level*3.15);state.pendingLevels++}if(state.pendingLevels>0&&state.mode==="playing")openUpgrade()}
  function burst(x,y,color,count=12,speed=130){for(let i=0;i<count;i++){const a=rand(0,TAU),s=rand(speed*.25,speed);state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,r:rand(1.4,4.8),life:rand(.25,.75),max:.75,color})}if(state.particles.length>340)state.particles.splice(0,state.particles.length-340)}

  const upgradePool=[
    {id:"twin",icon:"✦",name:"TWIN ARC",desc:"Add one projectile to every volley.",max:4,apply:p=>p.projectiles++},
    {id:"clock",icon:"⌁",name:"OVERCLOCK",desc:"Fire 18% faster.",max:5,apply:p=>p.fireRate*=.82},
    {id:"lance",icon:"➤",name:"PHASE LANCE",desc:"Deal 35% more damage.",max:5,apply:p=>p.damage*=1.35},
    {id:"pierce",icon:"◇",name:"GHOST ROUND",desc:"Projectiles pierce one more enemy.",max:3,apply:p=>p.pierce++},
    {id:"boots",icon:"⚡",name:"VOID BOOTS",desc:"Move 14% faster and dash sooner.",max:4,apply:p=>{p.speed*=1.14;p.dashMax=Math.max(.75,p.dashMax-.17)}},
    {id:"magnet",icon:"◎",name:"GRAVITY LOOP",desc:"Pull shards from much farther away.",max:4,apply:p=>p.magnet+=65},
    {id:"aegis",icon:"⬡",name:"AEGIS CORE",desc:"Gain 24 max health and fully repair.",max:3,apply:p=>{p.maxHp+=24;p.hp=p.maxHp}},
    {id:"drone",icon:"◉",name:"ORBIT DRONE",desc:"Add a damaging orbital drone.",max:3,apply:p=>p.drones++}
  ];
  function openUpgrade(){state.mode="upgrade";state.pendingLevels--;input.keys.clear();resetStick();ui.mobile.classList.remove("active");const available=upgradePool.filter(u=>(state.upgradeCounts[u.id]||0)<u.max),choices=[];while(choices.length<3&&available.length){const i=Math.floor(Math.random()*available.length);choices.push(available.splice(i,1)[0])}if(!choices.length){state.player.damage*=1.15;continueAfterUpgrade();return}ui.upgradeOptions.replaceChildren();for(const u of choices){const b=document.createElement("button");b.className="upgrade-option";b.innerHTML=`<i>${u.icon}</i><b>${u.name}</b><span>${u.desc}</span><small>LV ${(state.upgradeCounts[u.id]||0)+1}</small>`;b.addEventListener("click",()=>{state.upgradeCounts[u.id]=(state.upgradeCounts[u.id]||0)+1;u.apply(state.player);tone("level");toast(u.name+" ONLINE");continueAfterUpgrade()},{once:true});ui.upgradeOptions.append(b)}show(ui.upgrade,true);tone("level")}
  function continueAfterUpgrade(){show(ui.upgrade,false);if(state.pendingLevels>0){openUpgrade();return}state.mode="playing";state.last=performance.now();ui.mobile.classList.toggle("active",coarse);updateHud()}

  function update(dt){const p=state.player;state.time+=dt;state.remaining=Math.max(0,120-state.time);if(state.time>=100&&!state.bossSpawned)spawnBoss();const m=moveVector();p.invuln=Math.max(0,p.invuln-dt);p.dashCd=Math.max(0,p.dashCd-dt);if(p.dashT>0){p.dashT-=dt;p.vx=p.dashX*760;p.vy=p.dashY*760;burst(p.x,p.y,p.color,1,25)}else{const responsiveness=1-Math.exp(-dt*22);p.vx+=(m.x*p.speed-p.vx)*responsiveness;p.vy+=(m.y*p.speed-p.vy)*responsiveness}p.x+=p.vx*dt;p.y+=p.vy*dt;if(Math.hypot(p.vx,p.vy)>18)p.angle=Math.atan2(p.vy,p.vx);p.fireTimer-=dt;if(p.fireTimer<=0){shoot();p.fireTimer+=p.fireRate}
    const density=Math.min(95,9+Math.floor(state.time*.55));state.spawnTimer-=dt;if(state.spawnTimer<=0&&state.enemies.length<density){const bossSlow=state.boss?.hp>0?1.55:1;spawnEnemy();if(state.time>45&&Math.random()<.18)spawnEnemy("spark");state.spawnTimer=clamp((.92-state.time*.0054)*bossSlow,.18,1.1)}
    for(const e of state.enemies){e.phase+=dt*(e.boss?1.4:3.6);e.hit=Math.max(0,e.hit-dt);const a=Math.atan2(p.y-e.y,p.x-e.x),d=Math.hypot(p.x-e.x,p.y-e.y)||1;if(e.type==="wraith"&&d<430){const ideal=260,dir=d>ideal?1:-.35;e.x+=Math.cos(a)*e.speed*dir*dt;e.y+=Math.sin(a)*e.speed*dir*dt;e.shoot-=dt;if(e.shoot<=0){enemyShot(e);e.shoot=rand(1.6,2.5)}}else{e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt}if(e.boss){e.shoot-=dt;if(e.shoot<=0){enemyShot(e);e.shoot=Math.max(.65,1.6-state.time*.002);state.shake=4}}if(d<p.r+e.r*.72)hitPlayer(e.boss?19:e.type==="tank"?17:11,e)}
    for(const b of state.bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.dead)continue;for(const e of state.enemies){if(e.dead)continue;const rr=b.r+e.r;if(dist2(b,e)<rr*rr){e.hp-=b.damage;e.hit=.09;burst(b.x,b.y,b.color,3,45);if(e.hp<=0)kill(e);if(b.pierce>0)b.pierce--;else{b.dead=true;break}}}}
    for(const b of state.enemyBullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;const rr=b.r+p.r*.72;if(!b.dead&&dist2(b,p)<rr*rr){b.dead=true;hitPlayer(b.damage,b)}}
    if(p.drones){for(let i=0;i<p.drones;i++){const a=state.time*(1.8+i*.15)+i*TAU/p.drones,d={x:p.x+Math.cos(a)*55,y:p.y+Math.sin(a)*55};for(const e of state.enemies){if(e.dead)continue;const rr=8+e.r;if(dist2(d,e)<rr*rr){e.hp-=5.5*dt;e.hit=.05;if(e.hp<=0)kill(e)}}}}
    for(const s of state.shards){s.phase+=dt*4;s.x+=s.vx*dt;s.y+=s.vy*dt;s.vx*=Math.pow(.07,dt);s.vy*=Math.pow(.07,dt);const dx=p.x-s.x,dy=p.y-s.y,d=Math.hypot(dx,dy)||1;if(d<p.magnet){const pull=(1-d/p.magnet)*1050+150;s.x+=dx/d*pull*dt;s.y+=dy/d*pull*dt}if(d<p.r+s.r+4)gainShard(s)}
    for(const q of state.particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=Math.pow(.12,dt);q.vy*=Math.pow(.12,dt);q.life-=dt}
    state.enemies=state.enemies.filter(e=>!e.dead&&dist2(e,p)<2200*2200);state.bullets=state.bullets.filter(b=>!b.dead&&b.life>0);state.enemyBullets=state.enemyBullets.filter(b=>!b.dead&&b.life>0);state.shards=state.shards.filter(s=>!s.dead&&dist2(s,p)<1500*1500);state.particles=state.particles.filter(q=>q.life>0);if(state.comboTimer>0){state.comboTimer-=dt;if(state.comboTimer<=0)state.combo=1}state.shake=Math.max(0,state.shake-dt*22);if(state.toastTimer>0&&(state.toastTimer-=dt)<=0)ui.toast.classList.remove("show");updateHud()}
  function updateHud(){const p=state.player;if(!p)return;ui.hp.textContent=Math.ceil(p.hp);ui.hpFill.style.width=clamp(p.hp/p.maxHp*100,0,100)+"%";const sec=Math.ceil(state.remaining);ui.time.textContent=String(Math.floor(sec/60)).padStart(2,"0")+":"+String(sec%60).padStart(2,"0");ui.level.textContent=state.level;ui.xpFill.style.width=clamp(state.xp/state.xpNeed*100,0,100)+"%";ui.xpLabel.textContent=state.xp+" / "+state.xpNeed+" SHARDS";ui.combo.textContent="x"+state.combo;ui.combo.classList.toggle("hot",state.combo>=6);ui.dash.style.setProperty("--cooldown",p.dashCd>0?Math.round(p.dashCd/p.dashMax*100)+"%":"0%");if(state.boss)ui.bossFill.style.width=clamp(state.boss.hp/state.boss.maxHp*100,0,100)+"%"}

  function hash(x,y){let n=(x*374761393+y*668265263)^0x5bf03635;n=(n^(n>>13))*1274126177;return((n^(n>>16))>>>0)/4294967295}
  function screen(x,y){const p=state.player||{x:0,y:0};return{x:x-p.x+vw/2,y:y-p.y+vh/2}}
  function drawBackground(t){ctx.setTransform(dpr,0,0,dpr,0,0);const g=ctx.createLinearGradient(0,0,vw,vh);g.addColorStop(0,"#08051e");g.addColorStop(.48,"#11072e");g.addColorStop(1,"#041527");ctx.fillStyle=g;ctx.fillRect(0,0,vw,vh);const p=state.player||{x:t*8,y:t*3},grid=72,ox=(((-p.x)%grid)+grid)%grid,oy=(((-p.y)%grid)+grid)%grid;ctx.lineWidth=1;for(let x=ox-grid;x<vw+grid;x+=grid){ctx.strokeStyle="rgba(91,238,255,.075)";ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,vh);ctx.stroke()}for(let y=oy-grid;y<vh+grid;y+=grid){ctx.strokeStyle="rgba(157,90,255,.075)";ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(vw,y);ctx.stroke()}const tile=240,minX=Math.floor((p.x-vw/2)/tile)-1,maxX=Math.ceil((p.x+vw/2)/tile)+1,minY=Math.floor((p.y-vh/2)/tile)-1,maxY=Math.ceil((p.y+vh/2)/tile)+1;for(let gy=minY;gy<=maxY;gy++)for(let gx=minX;gx<=maxX;gx++){const h=hash(gx,gy);if(h<.46)continue;const s=screen(gx*tile+(h-.5)*110,gy*tile+(hash(gy,gx)-.5)*110),r=7+h*11;ctx.strokeStyle=h>.8?"rgba(255,72,211,.18)":"rgba(78,238,255,.13)";ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<6;i++){const a=i*TAU/6+(h*4),rr=i%2?r*.45:r,x=s.x+Math.cos(a)*rr,y=s.y+Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.stroke();ctx.fillStyle="rgba(7,4,26,.55)";ctx.fill()}const vignette=ctx.createRadialGradient(vw*.5,vh*.45,Math.min(vw,vh)*.12,vw*.5,vh*.5,Math.max(vw,vh)*.68);vignette.addColorStop(0,"rgba(0,0,0,0)");vignette.addColorStop(1,"rgba(0,0,18,.63)");ctx.fillStyle=vignette;ctx.fillRect(0,0,vw,vh)}
  function glowDot(x,y,r,color,alpha=1){ctx.globalAlpha=alpha*.18;ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r*2.2,0,TAU);ctx.fill();ctx.globalAlpha=alpha;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();ctx.globalAlpha=1}
  function polygon(x,y,r,sides,rotation=0){ctx.beginPath();for(let i=0;i<sides;i++){const a=rotation+i*TAU/sides,px=x+Math.cos(a)*r,py=y+Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath()}
  function drawShard(s){const q=screen(s.x,s.y),pulse=1+Math.sin(s.phase)*.12;ctx.save();ctx.translate(q.x,q.y);ctx.rotate(s.phase*.35);ctx.fillStyle="#6cffff";ctx.globalAlpha=.18;polygon(0,0,s.r*3.2*pulse,4,Math.PI/4);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle="#dcffff";polygon(0,0,s.r*1.45*pulse,4,Math.PI/4);ctx.fill();ctx.restore()}
  function drawBullet(b,enemy=false){const q=screen(b.x,b.y);glowDot(q.x,q.y,b.r,enemy?b.color:b.color);ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(q.x,q.y,Math.max(1.5,b.r*.38),0,TAU);ctx.fill()}
  function drawEnemy(e){const q=screen(e.x,e.y),hit=e.hit>0;ctx.save();ctx.translate(q.x,q.y);ctx.rotate(e.phase*.18);ctx.globalAlpha=.23;ctx.fillStyle=e.color;ctx.beginPath();ctx.arc(0,0,e.r*1.75,0,TAU);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle="rgba(0,0,15,.48)";ctx.beginPath();ctx.ellipse(4,e.r*.72,e.r*1.02,e.r*.38,0,0,TAU);ctx.fill();const fill=ctx.createRadialGradient(-e.r*.25,-e.r*.32,2,0,0,e.r*1.15);fill.addColorStop(0,hit?"#fff":e.color);fill.addColorStop(.5,e.boss?"#7d1e9c":"#182257");fill.addColorStop(1,"#070619");ctx.fillStyle=fill;ctx.strokeStyle=hit?"#fff":e.color;ctx.lineWidth=e.boss?4:2.5;if(e.type==="spark"){polygon(0,0,e.r,4,Math.PI/4);ctx.fill();ctx.stroke()}else if(e.type==="blade"){polygon(0,0,e.r,6,e.phase*.08);ctx.fill();ctx.stroke();for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(Math.cos(i*TAU/3)*e.r*1.45,Math.sin(i*TAU/3)*e.r*1.45);ctx.stroke()}}else if(e.type==="tank"){polygon(0,0,e.r,8,Math.PI/8);ctx.fill();ctx.stroke();ctx.strokeStyle="rgba(255,255,255,.5)";polygon(0,0,e.r*.67,8,Math.PI/8);ctx.stroke()}else if(e.type==="wraith"){ctx.beginPath();ctx.moveTo(e.r,0);for(let i=1;i<10;i++){const a=i*TAU/10,rr=i%2?e.r*.62:e.r;ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr)}ctx.closePath();ctx.fill();ctx.stroke()}else{polygon(0,0,e.r,10,e.phase*.04);ctx.fill();ctx.stroke();ctx.strokeStyle="#ff8dec";ctx.lineWidth=3;for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(Math.cos(i*TAU/5)*e.r*.45,Math.sin(i*TAU/5)*e.r*.45);ctx.lineTo(Math.cos(i*TAU/5)*e.r*1.45,Math.sin(i*TAU/5)*e.r*1.45);ctx.stroke()}}ctx.rotate(-e.phase*.18);ctx.fillStyle="#fff";ctx.beginPath();ctx.ellipse(e.r*.2,-e.r*.08,e.r*.22,e.r*.12,-.15,0,TAU);ctx.fill();ctx.fillStyle=e.boss?"#ff255f":"#09162e";ctx.beginPath();ctx.arc(e.r*.25,-e.r*.08,e.r*.065,0,TAU);ctx.fill();if(e.hp<e.maxHp&&!e.boss){ctx.fillStyle="rgba(4,3,20,.8)";ctx.fillRect(-e.r,e.r+7,e.r*2,3);ctx.fillStyle=e.color;ctx.fillRect(-e.r,e.r+7,e.r*2*clamp(e.hp/e.maxHp,0,1),3)}ctx.restore()}
  function drawPlayer(){const p=state.player,q=screen(p.x,p.y),blink=p.invuln>0&&Math.floor(p.invuln*18)%2===0;ctx.save();ctx.translate(q.x,q.y);ctx.rotate(p.angle);ctx.globalAlpha=blink?.45:1;ctx.fillStyle="rgba(0,0,15,.5)";ctx.beginPath();ctx.ellipse(-2,17,25,9,0,0,TAU);ctx.fill();const thrust=Math.hypot(p.vx,p.vy)>30?15:7;ctx.fillStyle=p.accent;ctx.globalAlpha=.25;ctx.beginPath();ctx.moveTo(-17,-7);ctx.lineTo(-17-thrust,0);ctx.lineTo(-17,7);ctx.fill();ctx.globalAlpha=blink?.45:1;ctx.fillStyle="#11113d";ctx.strokeStyle=p.color;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-14,-14);ctx.quadraticCurveTo(7,-23,18,-4);ctx.lineTo(16,13);ctx.quadraticCurveTo(0,23,-15,11);ctx.closePath();ctx.fill();ctx.stroke();const helmet=ctx.createRadialGradient(3,-9,2,2,-4,19);helmet.addColorStop(0,"#fff");helmet.addColorStop(.14,p.color);helmet.addColorStop(.55,"#2557b6");helmet.addColorStop(1,"#09082c");ctx.fillStyle=helmet;ctx.beginPath();ctx.arc(3,-6,16,0,TAU);ctx.fill();ctx.stroke();ctx.fillStyle="#07102e";ctx.beginPath();ctx.ellipse(9,-8,10,5,-.12,0,TAU);ctx.fill();ctx.strokeStyle="rgba(255,255,255,.75)";ctx.lineWidth=1.5;ctx.stroke();ctx.fillStyle=p.accent;ctx.beginPath();ctx.moveTo(-9,4);ctx.lineTo(-35+Math.sin(state.time*8)*5,12);ctx.lineTo(-12,12);ctx.closePath();ctx.fill();ctx.globalAlpha=1;ctx.restore();if(p.drones){for(let i=0;i<p.drones;i++){const a=state.time*(1.8+i*.15)+i*TAU/p.drones,x=q.x+Math.cos(a)*55,y=q.y+Math.sin(a)*55;glowDot(x,y,7,p.accent);ctx.strokeStyle="#fff";ctx.lineWidth=1.5;polygon(x,y,5,4,a);ctx.stroke()}}}
  function drawParticles(){for(const p of state.particles){const q=screen(p.x,p.y),a=clamp(p.life/p.max,0,1);ctx.globalAlpha=a;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(q.x,q.y,p.r*a,0,TAU);ctx.fill()}ctx.globalAlpha=1}
  function drawScene(){drawBackground(state.time);ctx.save();if(state.shake>0)ctx.translate(rand(-state.shake,state.shake),rand(-state.shake,state.shake));for(const s of state.shards)drawShard(s);for(const b of state.bullets)drawBullet(b);for(const b of state.enemyBullets)drawBullet(b,true);for(const e of state.enemies)drawEnemy(e);drawPlayer();drawParticles();ctx.restore()}
  function drawMenu(t){drawBackground(t);const cx=vw*.5,cy=vh*.53;ctx.globalAlpha=.12;ctx.strokeStyle="#5ff8ff";ctx.lineWidth=2;for(let i=0;i<5;i++){ctx.beginPath();ctx.arc(cx,cy,80+i*48+Math.sin(t+i)*8,0,TAU);ctx.stroke()}ctx.globalAlpha=1}
  function frame(now){const dt=Math.min(.033,Math.max(.001,(now-state.last||now)/1000));state.last=now;state.ambient+=dt;if(state.mode==="playing")update(dt);if(state.mode==="menu")drawMenu(state.ambient);else if(state.player)drawScene();requestAnimationFrame(frame)}

  function resetStick(){input.stick.x=0;input.stick.y=0;input.stick.id=null;ui.stick.style.setProperty("--sx","0px");ui.stick.style.setProperty("--sy","0px")}
  function moveStick(e){if(e.pointerId!==input.stick.id)return;const r=ui.stick.getBoundingClientRect(),radius=r.width*.31,dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),l=Math.hypot(dx,dy)||1,k=Math.min(1,radius/l),x=dx*k,y=dy*k;input.stick.x=x/radius;input.stick.y=y/radius;ui.stick.style.setProperty("--sx",x+"px");ui.stick.style.setProperty("--sy",y+"px")}
  ui.stick.addEventListener("pointerdown",e=>{e.preventDefault();input.stick.id=e.pointerId;ui.stick.setPointerCapture(e.pointerId);moveStick(e)});ui.stick.addEventListener("pointermove",moveStick);ui.stick.addEventListener("pointerup",resetStick);ui.stick.addEventListener("pointercancel",resetStick);ui.stick.addEventListener("lostpointercapture",resetStick);ui.dash.addEventListener("pointerdown",e=>{e.preventDefault();dash()});
  addEventListener("keydown",e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown","w","a","s","d"," "].includes(k))e.preventDefault();if(k===" "){if(!e.repeat)dash();return}input.keys.add(k);if(k==="Escape"){if(state.mode==="playing")pause();else if(state.mode==="paused")resume()}});addEventListener("keyup",e=>input.keys.delete(e.key.length===1?e.key.toLowerCase():e.key));addEventListener("blur",()=>{input.keys.clear();resetStick();if(!coarse&&state.mode==="playing")pause()});document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.mode==="playing")pause()});addEventListener("resize",resize,{passive:true});
  const stopGesture=e=>{if(e.cancelable)e.preventDefault()};["gesturestart","gesturechange","gestureend"].forEach(type=>document.addEventListener(type,stopGesture,{passive:false}));document.addEventListener("touchmove",stopGesture,{passive:false});document.addEventListener("dblclick",stopGesture,{passive:false});let lastTouch=0;document.addEventListener("touchend",e=>{const now=Date.now();if(now-lastTouch<360&&e.cancelable)e.preventDefault();lastTouch=now},{passive:false});
  document.querySelectorAll(".hunter").forEach(b=>b.addEventListener("click",()=>setHunter(b.dataset.hunter)));ui.play.addEventListener("click",start);ui.pauseBtn.addEventListener("click",pause);ui.resume.addEventListener("click",resume);ui.quit.addEventListener("click",menu);ui.again.addEventListener("click",start);ui.home.addEventListener("click",menu);ui.victoryAgain.addEventListener("click",start);ui.victoryHome.addEventListener("click",menu);
  if(new URLSearchParams(location.search).has("test"))window.__RIFT_RUSH_DIAGNOSTICS__=()=>({mode:state.mode,time:state.time,score:state.score,kills:state.kills,level:state.level,xp:state.xp,player:state.player?{x:state.player.x,y:state.player.y,hp:state.player.hp,speed:state.player.speed,projectiles:state.player.projectiles,dashCd:state.player.dashCd}:null,enemies:state.enemies.length,bullets:state.bullets.length,shards:state.shards.length,boss:state.boss?{hp:state.boss.hp,maxHp:state.boss.maxHp}:null});
  resize();setHunter("ion");requestAnimationFrame(frame);
})();
