/* Bubble Riot v4 · native canvas bubbles over an original illustrated garden. */
(()=>{'use strict';
const R=window.ZeroRiot,$=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const palette=[['#efedff','#ac8bec','#7254b7'],['#fff1df','#ffb07f','#d77858'],['#e5fff5','#79d8bf','#35a792'],['#fbe9ff','#d597e5','#a55fb2'],['#e5f7ff','#84cdf0','#4c9fc3'],['#fff8d5','#f4d273','#c39d45']];
let seed=new URLSearchParams(location.search).get('seed')||new Date().toISOString().slice(0,10);seed=seed.replace(/[^a-zA-Z0-9-]/g,'').slice(0,32)||'garden';$('seed').value=seed;
let g=R.create(seed),mode='menu',last=0,clock=0,endDelay=0,toastTime=0,recoil=0,keys={},pointer=null,particles=[],rings=[],floaters=[],drops=[],rescues=[],celebration=null,flash=0,sound=false,audioCtx=null;
const reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
function tone(freq,duration=.12,volume=.06,delay=0){if(!sound)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),gain=audioCtx.createGain(),t=audioCtx.currentTime+delay;o.type='sine';o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(freq*1.3,t+duration);gain.gain.setValueAtTime(volume,t);gain.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(gain);gain.connect(audioCtx.destination);o.start(t);o.stop(t+duration);}catch{}}
function say(message,seconds=2.5){$('toast').textContent=message;$('toast').classList.add('visible');toastTime=seconds;}
function panel(id){$('overlay').hidden=!id;['intro','pause-panel','results'].forEach(p=>$(p).hidden=p!==id);}
function clearInput(){keys={};pointer=null;}
function play(state){g=state;mode='play';endDelay=0;clearInput();particles=[];rings=[];floaters=[];drops=[];rescues=[];celebration=null;flash=0;panel(null);setWorld();say(`${R.operationName(g)} to make ${g.config.target}. Save the Lumis!`,3);updateHUD();}
function setWorld(){const w=R.world(g);$('board-wrap').setAttribute('data-world',String(w));for(let i=0;i<3;i++)$('world'+i).setAttribute('aria-current',i===w?'step':'false');}
function start(){seed=$('seed').value.replace(/[^a-zA-Z0-9-]/g,'').slice(0,32)||new Date().toISOString().slice(0,10);$('seed').value=seed;play(R.create(seed));}
function pause(){if(mode==='play'&&!g.ended){mode='paused';clearInput();panel('pause-panel');}else if(mode==='paused'){mode='play';panel(null);}}
function burst(x,y,color,count){for(let i=0;i<(reduced?4:count);i++){const a=Math.random()*Math.PI*2,s=70+Math.random()*230;particles.push({x,y,dx:Math.cos(a)*s,dy:Math.sin(a)*s-60,life:.5+Math.random()*.45,max:1,color,r:3+Math.random()*6});}if(particles.length>450)particles.splice(0,particles.length-450);}
function events(){for(const e of g.events){
 if(e.type==='shoot'){recoil=1;tone(330,.1,.035);}
 else if(e.type==='bounce'){rings.push({x:e.x,y:e.y,r:10,life:.35,color:'#fff'});tone(650,.08,.02);}
 else if(e.type==='pop'){
  for(const b of e.popped){burst(b.x,b.y,palette[b.color][1],12);rings.push({x:b.x,y:b.y,r:32,life:.5,color:palette[b.color][1]});}
  for(const b of e.dropped)drops.push({...b,dy:40,dx:(Math.random()-.5)*170,life:1.8});
  for(const b of e.rescued)rescues.push({x:b.x,y:b.y,dx:(b.x<360?-1:1)*65,life:2,phase:b.id});
  for(const b of e.explosions){burst(b.x,b.y,'#ffbc42',30);rings.push({x:b.x,y:b.y,r:50,life:.8,color:'#ffcc48'});}
  flash=e.explosions.length?.16:.04;
  celebration={text:e.explosions.length?'BOOM!':e.rowsCleared>0?'ROW CLEAR!':e.bankShot?'TRICK SHOT!':e.rescued.length?'LUMI SAVED!':`COMBO ×${e.combo}`,sub:e.rescued.length?`${e.rescued.length} LUMI${e.rescued.length>1?'S':''} RESCUED`:`+${e.points} POINTS`,life:1.45};
  floaters.push({x:e.x,y:e.y,text:`+${e.points}`,life:1.3});say(e.message+(e.rescued.length?` · ${e.rescued.length} rescued!`:e.dropped.length?` · ${e.dropped.length} bonus drops!`:''));
  [523,659,784].forEach((f,i)=>tone(f+e.combo*30,.16,.035,i*.045));if(e.explosions.length)tone(110,.32,.06);if(e.rescued.length)tone(1318,.3,.035,.17);
 }else if(e.type==='ready'){tone(1047,.35,.04);}
 else if(e.type==='miss'){say(e.message,3.4);tone(220,.17,.03);}
 else if(e.type==='end'){endDelay=1.7;}
 }g.events=[];if(g.rainbowReady&&!g.ended)say('RAINBOW READY! Any number. Bigger blast!');updateHUD();}
function finish(){mode='end';clearInput();panel('results');$('result-title').textContent=g.campaignComplete?'ALL 12 GARDENS CLEARED!':`GARDEN ${g.level} CLEARED!`;$('stars').textContent='★'.repeat(g.stars)+'☆'.repeat(3-g.stars);$('result-heading').textContent=g.campaignComplete?'You’re a pop star!':g.stars===3?'Pop perfection!':'Beautifully popped!';$('result-stats').textContent=`${g.score.toLocaleString()} points · ${g.shots} shots · ${g.totalStars} stars · ${g.totalRescued} Lumis rescued. ${g.campaignComplete?'All worlds are safe!' :'Every bubble is gone. Ready for a new target?'}`;$('next').textContent=g.campaignComplete?'PLAY AGAIN →':'NEXT GARDEN →';$('share-status').textContent='';try{localStorage.setItem('bubble-riot-v4-best',String(Math.max(g.score,Number(localStorage.getItem('bubble-riot-v4-best'))||0)));}catch{}[523,659,784,1047].forEach((f,i)=>tone(f,.3,.04,i*.12));}
function fire(){if(mode==='play'&&R.shoot(g)){events();return true;}return false;}
function choose(i){if(mode==='play'){R.select(g,i);tone(450+i*100,.08,.02);updateHUD();}}
function updateHUD(){ const levelMarkup=`${g.level} <small>/ 12</small>`;if($('level').innerHTML!==levelMarkup)$('level').innerHTML=levelMarkup;$('target').textContent=g.config.target;$('remaining').textContent=g.bubbles.length;$('score').textContent=g.score.toLocaleString();$('level-name').textContent=g.config.name;$('op-label').textContent=R.operationName(g)+' TO RESCUE';$('rescue-count').textContent=`LUMIS ${g.rescued} / ${g.lumiTotal}`;for(let i=0;i<3;i++){const b=$('ammo'+i);b.querySelector('span').textContent=g.config.op+g.ammo[i];b.setAttribute('aria-pressed',String(g.selected===i));b.disabled=mode!=='play'||!!g.projectile||g.ended;}$('fire').disabled=mode!=='play'||!!g.projectile||g.cooldown>0||g.ended;$('fire').firstChild.textContent=g.rainbowReady?'RAINBOW! ':'FIRE! ';$('power-label').textContent=g.rainbowReady?'READY!':`${g.power} / 3`;$('power-fill').style.width=(g.rainbowReady?100:g.power/3*100)+'%';$('pause').disabled=mode!=='play'&&mode!=='paused';$('hint').disabled=mode!=='play'||!!g.projectile||g.ended;}
function updateAim(x,y){const box=canvas.getBoundingClientRect();R.aim(g,(x-box.left)*R.W/box.width,(y-box.top)*R.H/box.height);}
canvas.addEventListener('pointerdown',e=>{if(mode!=='play'||g.projectile||g.ended||e.button>0)return;e.preventDefault();canvas.focus({preventScroll:true});pointer=e.pointerId;canvas.setPointerCapture(e.pointerId);updateAim(e.clientX,e.clientY);});
canvas.addEventListener('pointermove',e=>{if(mode==='play'&&!g.projectile&&(e.pointerType==='mouse'||pointer===e.pointerId))updateAim(e.clientX,e.clientY);});
canvas.addEventListener('pointerup',e=>{if(pointer!==e.pointerId)return;pointer=null;const box=canvas.getBoundingClientRect();if(e.clientX>=box.left&&e.clientX<=box.right&&e.clientY>=box.top&&e.clientY<=box.bottom){updateAim(e.clientX,e.clientY);fire();}});
canvas.addEventListener('pointercancel',()=>pointer=null);canvas.addEventListener('lostpointercapture',()=>pointer=null);
window.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;if(e.code==='Escape'||e.code==='KeyP'){if(!e.repeat)pause();return;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space','Digit1','Digit2','Digit3'].includes(e.code)){e.preventDefault();if(mode==='play'){keys[e.code]=true;if(!e.repeat){if(e.code==='Space')fire();if(/^Digit[123]$/.test(e.code))choose(Number(e.code.slice(-1))-1);}}}});
window.addEventListener('keyup',e=>delete keys[e.code]);window.addEventListener('blur',()=>{clearInput();if(mode==='play'&&!g.ended)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(mode==='play'&&!g.ended)pause();}});
$('start').addEventListener('click',start);$('resume').addEventListener('click',pause);$('pause').addEventListener('click',pause);$('restart').addEventListener('click',()=>play(R.retryLevel(g)));$('retry').addEventListener('click',()=>play(R.retryLevel(g)));$('next').addEventListener('click',()=>play(g.campaignComplete?R.create(g.seed):R.nextLevel(g)));$('random').addEventListener('click',()=>$('seed').value='G'+Math.floor(Math.random()*999999));$('fire').addEventListener('click',fire);for(let i=0;i<3;i++)$('ammo'+i).addEventListener('click',()=>choose(i));
$('sound').addEventListener('click',()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));tone(660);});
$('hint').addEventListener('click',()=>{if(mode!=='play'||g.projectile||g.ended)return;for(let i=0;i<=240;i++){const angle=-1.16+i*2.32/240,b=g.bubbles.find(q=>q.id===R.trace(g,angle).hitId);if(!b)continue;const n=R.required(g,b.v),slot=g.ammo.indexOf(n);if(slot>=0){g.angle=angle;R.select(g,slot);say(`${b.v} ${g.config.op} ${n} = ${g.config.target}. Press FIRE!`,4);updateHUD();return;}}say('Try bouncing off the side wall.');});
$('share').addEventListener('click',async()=>{const url=new URL(location.href);url.search='';url.searchParams.set('seed',g.seed);const message=`Bubble Riot: ${g.score} points, ${g.totalStars} stars, ${g.level}/12 levels, ${g.totalRescued} Lumis saved. Try my adventure! ${url}`;try{await navigator.clipboard.writeText(message);$('share-status').textContent='Challenge copied! Send it to a friend.';}catch{$('share-status').textContent=message;}});
function circle(x,y,r,color){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
function bubble(x,y,r,value,color=0,alpha=1){ctx.save();ctx.globalAlpha=alpha;const p=palette[color%6];ctx.shadowColor='#48618735';ctx.shadowBlur=10;ctx.shadowOffsetY=5;const fill=ctx.createRadialGradient(x-r*.32,y-r*.45,r*.03,x+r*.2,y+r*.25,r*1.35);fill.addColorStop(0,p[0]);fill.addColorStop(.4,p[1]);fill.addColorStop(1,p[2]);circle(x,y,r,fill);ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.lineWidth=2;ctx.strokeStyle='#ffffffb0';ctx.stroke();ctx.beginPath();ctx.ellipse(x-r*.27,y-r*.53,r*.34,r*.12,-.4,0,Math.PI*2);ctx.fillStyle='#ffffffbb';ctx.fill();ctx.beginPath();ctx.arc(x,y,r*.82,.2,1.22);ctx.lineWidth=3;ctx.strokeStyle='#ffffff5c';ctx.stroke();ctx.fillStyle='#29344b';ctx.font=`900 ${r*.93}px "Trebuchet MS",Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(value),x,y+r*.09);ctx.restore();}
function star(x,y,r,color,rotation=0){ctx.save();ctx.translate(x,y);ctx.rotate(rotation);ctx.beginPath();for(let i=0;i<10;i++){const a=i*Math.PI/5-Math.PI/2,rr=i%2?r*.45:r;const px=Math.cos(a)*rr,py=Math.sin(a)*rr;i?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.closePath();ctx.fillStyle=color;ctx.fill();ctx.restore();}
// Lumis are gameplay creatures: their badge never covers the arithmetic label.
function lumi(x,y,r,phase=0,happy=false){ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(clock*3+phase)*.1);ctx.shadowColor='#ffd83a';ctx.shadowBlur=happy?18:5;star(0,0,r,'#ffe370');ctx.shadowBlur=0;const blink=!happy&&Math.sin(clock*.9+phase)>.994;for(const side of [-1,1]){ctx.fillStyle='#4b4368';ctx.beginPath();ctx.ellipse(side*r*.24,-r*.08,r*.1,blink?r*.025:r*.16,0,0,Math.PI*2);ctx.fill();circle(side*r*.34,r*.19,r*.1,'#ff9d8a');}ctx.beginPath();ctx.arc(0,r*.15,r*.16,0,Math.PI);ctx.lineWidth=Math.max(1,r*.06);ctx.strokeStyle='#785265';ctx.stroke();ctx.restore();}
function specialBubble(b,alpha=1){bubble(b.x,b.y,R.BR,b.lumi?'':b.v,b.color,alpha);ctx.save();ctx.globalAlpha=alpha;if(b.lumi){ctx.fillStyle='#29344b';ctx.font='900 26px "Trebuchet MS",Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(b.v),b.x,b.y-8);lumi(b.x,b.y+23,14,b.id);}if(b.bomb){circle(b.x+22,b.y-23,13,'#ff7844');star(b.x+22,b.y-23,9,'#fff4ab',clock*.7);ctx.beginPath();ctx.arc(b.x,b.y,35,0,Math.PI*2);ctx.lineWidth=2;ctx.strokeStyle='#ffa13f';ctx.stroke();}ctx.restore();}
function render(dt){ctx.clearRect(0,0,R.W,R.H);const haze=ctx.createLinearGradient(0,0,0,600);haze.addColorStop(0,'#e0fff122');haze.addColorStop(1,'#fff5ff00');ctx.fillStyle=haze;ctx.fillRect(0,0,720,900);
 if(R.world(g)===2){for(let i=0;i<22;i++){const x=48+(i*157)%630,y=48+(i*97)%650;ctx.globalAlpha=.25+.35*(1+Math.sin(clock*1.6+i))/2;star(x,y,2+i%3,'#d8fff8',.2);}ctx.globalAlpha=1;}
 // Fixed anchor rail makes hanging groups and bonus drops legible.
 ctx.beginPath();ctx.moveTo(55,77);ctx.quadraticCurveTo(360,99,665,77);ctx.strokeStyle='#709da55e';ctx.lineWidth=4;ctx.stroke();for(const b of g.bubbles)if(b.row===0){ctx.beginPath();ctx.moveTo(b.x,86);ctx.lineTo(b.x,b.y-30);ctx.strokeStyle='#8ba7a678';ctx.lineWidth=2;ctx.stroke();}
 const preview=R.trace(g);const hit=g.bubbles.find(b=>b.id===preview.hitId);$('equation').textContent=g.rainbowReady?'ANY NUMBER!':hit?`${hit.v} ${g.config.op} ${g.ammo[g.selected]} = ?`:`? ${g.config.op} ${g.ammo[g.selected]} = ${g.config.target}`;$('instruction').textContent=g.rainbowReady?'Your next shot makes a rainbow blast.':`Aim at a bubble. Make ${g.config.target}.`;
 if(mode==='play'&&!g.projectile&&!g.ended){let offset=clock*26%20;for(let i=1;i<preview.points.length;i++){const a=preview.points[i-1],b=preview.points[i],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy);for(let t=offset;t<len;t+=20){circle(a.x+dx*t/len,a.y+dy*t/len,3.2,g.rainbowReady?'#c96edf':'#fff');}offset=(offset-len)%20;if(offset<0)offset+=20;}}
 for(const b of g.bumpers){ctx.save();ctx.shadowBlur=13;ctx.shadowColor='#8f66c750';const f=ctx.createRadialGradient(b.x-15,b.y-18,2,b.x,b.y,b.r);f.addColorStop(0,'#fffdf2');f.addColorStop(.6,'#f4e4ff');f.addColorStop(1,'#a985d4');circle(b.x,b.y,b.r,f);ctx.shadowBlur=0;ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();star(b.x,b.y,22,'#b494d8',Math.sin(clock)*.12);ctx.restore();}
 for(const b of g.bubbles){specialBubble(b);if(hit&&hit.id===b.id&&mode==='play'&&!g.projectile){ctx.beginPath();ctx.arc(b.x,b.y,38,0,Math.PI*2);ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();}}
 for(const d of drops)specialBubble({...d,lumi:false},Math.min(1,d.life));
 for(const l of rescues)lumi(l.x,l.y,26,l.phase,true);
 // A toy launcher with a little face; barrel rotates exactly with the ray model.
 ctx.save();ctx.translate(R.CX,R.CY+recoil*7);ctx.shadowColor='#52629630';ctx.shadowBlur=15;circle(0,14,56,'#7657c3');ctx.shadowBlur=0;ctx.save();ctx.rotate(g.angle);ctx.fillStyle='#8d71cf';ctx.beginPath();ctx.roundRect(-23,-65,46,70,12);ctx.fill();ctx.fillStyle='#d8c7fc';ctx.beginPath();ctx.roundRect(-27,-65,54,18,7);ctx.fill();ctx.restore();circle(0,8,45,'#bfa4ed');circle(-15,15,4,'#46355d');circle(15,15,4,'#46355d');ctx.beginPath();ctx.arc(0,24,7,0,Math.PI);ctx.strokeStyle='#634579';ctx.lineWidth=3;ctx.stroke();circle(-25,23,7,'#edb8dc');circle(25,23,7,'#edb8dc');ctx.restore();
 if(!g.projectile&&!g.ended){bubble(R.CX,R.CY-17,24,g.rainbowReady?'★':g.ammo[g.selected],g.rainbowReady?3:1);if(g.rainbowReady)for(let i=0;i<6;i++){const a=clock*2+i*Math.PI/3;star(R.CX+Math.cos(a)*43,R.CY-17+Math.sin(a)*43,6,palette[i][1],a);}}
 if(g.projectile){const p=g.projectile;for(let i=4;i>0;i--)circle(p.x-p.dx*i*10,p.y-p.dy*i*10,Math.max(2,12-i*2),p.rainbow?palette[i%6][1]:'#ffffffe0');bubble(p.x,p.y,R.SR,p.rainbow?'★':p.value,p.rainbow?3:1);}
 if(flash>0&&!reduced){ctx.fillStyle=`rgba(255,224,134,${flash})`;ctx.fillRect(0,0,720,900);}
 if(celebration){const e=celebration;ctx.save();ctx.globalAlpha=Math.min(1,e.life*2);ctx.translate(360,456);const size=reduced?1:1+Math.max(0,e.life-1.15)*.35;ctx.scale(size,size);ctx.font='900 51px "Trebuchet MS",Arial';ctx.textAlign='center';ctx.lineWidth=8;ctx.strokeStyle='#fff';ctx.strokeText(e.text,0,0);ctx.fillStyle='#b547a0';ctx.fillText(e.text,0,0);ctx.font='900 18px "Trebuchet MS",Arial';ctx.lineWidth=5;ctx.strokeText(e.sub,0,35);ctx.fillStyle='#73468b';ctx.fillText(e.sub,0,35);ctx.restore();}
 for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);star(p.x,p.y,p.r,p.color,p.life*4);}ctx.globalAlpha=1;
 for(const r of rings){ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.strokeStyle=r.color;ctx.globalAlpha=Math.max(0,r.life*1.5);ctx.lineWidth=4;ctx.stroke();}ctx.globalAlpha=1;
 for(const f of floaters){ctx.globalAlpha=Math.min(1,f.life);ctx.font='900 34px "Trebuchet MS",Arial';ctx.textAlign='center';ctx.strokeStyle='#fff';ctx.lineWidth=5;ctx.strokeText(f.text,f.x,f.y);ctx.fillStyle='#7252ab';ctx.fillText(f.text,f.x,f.y);}ctx.globalAlpha=1;
}
function frame(now){const dt=Math.min(.04,Math.max(0,(now-last)/1000));last=now;if(mode!=='paused'){clock+=dt;recoil=Math.max(0,recoil-dt*6);flash=Math.max(0,flash-dt*.65);if(celebration){celebration.life-=dt;if(celebration.life<=0)celebration=null;}for(const l of rescues){l.x+=l.dx*dt+Math.sin(clock*7+l.phase)*dt*20;l.y-=160*dt;l.life-=dt;}rescues=rescues.filter(l=>l.life>0);if(mode==='play'){if(!g.projectile){const a=(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0);g.angle=Math.max(-1.16,Math.min(1.16,g.angle+a*dt*1.05));}R.step(g,dt);if(g.events.length)events();if(endDelay>0){endDelay-=dt;if(endDelay<=0)finish();}updateHUD();}for(const p of particles){p.x+=p.dx*dt;p.y+=p.dy*dt;p.dy+=300*dt;p.life-=dt;}particles=particles.filter(p=>p.life>0);for(const r of rings){r.r+=90*dt;r.life-=dt;}rings=rings.filter(r=>r.life>0);for(const f of floaters){f.y-=46*dt;f.life-=dt;}floaters=floaters.filter(f=>f.life>0);for(const d of drops){d.x+=d.dx*dt;d.y+=d.dy*dt;d.dy+=800*dt;d.life-=dt;}drops=drops.filter(d=>d.life>0&&d.y<980);if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').classList.remove('visible');}}
 render(dt);requestAnimationFrame(frame);}
setWorld();updateHUD();requestAnimationFrame(frame);
})();
