(()=>{
  "use strict";
  const TAU=Math.PI*2,canvas=document.querySelector("#game"),ctx=canvas.getContext("2d",{alpha:false,desynchronized:true});
  const astronaut=new Image(),mothership=new Image();astronaut.src="assets/astronaut.webp";mothership.src="assets/mothership.webp";
  const $=s=>document.querySelector(s),ui={menu:$("#menu"),hud:$("#hud"),over:$("#gameover"),landed:$("#landed"),complete:$("#complete"),pause:$("#pause"),play:$("#play-btn"),retry:$("#retry-btn"),home:$("#home-btn"),next:$("#next-btn"),again:$("#again-btn"),completeHome:$("#complete-home-btn"),pauseBtn:$("#pause-btn"),resume:$("#resume-btn"),quit:$("#quit-btn"),target:$("#target-name"),speed:$("#speed"),gamma:$("#gamma"),seeds:$("#seeds"),distance:$("#distance-fill"),distanceLabel:$("#distance-label"),alert:$("#alert"),warning:$("#speed-warning"),deathTitle:$("#death-title"),deathCopy:$("#death-copy"),landedName:$("#landed-name"),landedCopy:$("#landed-copy"),mobile:$("#mobile-controls"),joystick:$("#joystick"),fire:$("#fire-btn")};
  const worlds=[
    {name:"MARS",color:"#df643f",dark:"#6d1d2a",accent:"#ffb25f",copy:"Dormant minerals meet the first seeds beneath a rust-red sky."},
    {name:"VENUS",color:"#f0b34e",dark:"#8b4529",accent:"#fff0a8",copy:"Life enters the high clouds, far above the crushing surface."},
    {name:"JUPITER",color:"#d8a477",dark:"#694455",accent:"#fff0ce",bands:true,copy:"The seeds drift into the giant planet's temperate cloud layers."},
    {name:"SATURN",color:"#e5ca89",dark:"#6c5572",accent:"#fff6bb",bands:true,rings:true,copy:"Living chemistry begins among Saturn's luminous storms."},
    {name:"URANUS",color:"#74d9dc",dark:"#295c87",accent:"#d0ffff",rings:true,copy:"A fragile biosphere wakes in the blue-green upper atmosphere."},
    {name:"NEPTUNE",color:"#3974ef",dark:"#172f86",accent:"#8eefff",bands:true,copy:"Life reaches the final blue frontier of the Solar System."}
  ];
  const input={keys:new Set(),touches:new Map(),stick:{x:0,y:0,pointerId:null},fire:false},state={running:false,paused:false,level:0,seeded:0,time:0,proper:0,last:0,cam:0,targetX:3600,nextHazard:620,nextWell:1050,player:null,hazards:[],wells:[],shots:[],particles:[],stars:[],intro:0,alertTimer:0,fireCooldown:0,loopToken:0};
  let vw=innerWidth,vh=innerHeight,dpr=1,audio=null;const coarse=matchMedia("(pointer: coarse)").matches||/(?:^|[?&])mobile=1/.test(location.search),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),show=(n,on)=>n.classList.toggle("active",on);
  function resize(){vw=innerWidth;vh=innerHeight;dpr=Math.min(devicePixelRatio||1,coarse?1.2:1.65);canvas.width=Math.round(vw*dpr);canvas.height=Math.round(vh*dpr);canvas.style.width=vw+"px";canvas.style.height=vh+"px";ctx.setTransform(dpr,0,0,dpr,0,0);state.stars=Array.from({length:coarse?95:150},(_,i)=>({x:(i*149.7)%vw,y:(i*83.1)%vh,r:.45+i%4*.32,p:.08+(i%4)*.055,c:i%11===0?"#b897ff":i%7===0?"#78f6ff":"#fff"}));if(state.player){state.player.x=clamp(state.player.x,vw*.15,vw*.72);state.player.y=clamp(state.player.y,80,vh-70)}draw()}
  function initAudio(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume()}
  function sound(kind){if(!audio)return;const now=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type=kind==="seed"?"sine":kind==="hit"||kind==="explode"?"sawtooth":"triangle";const a=kind==="seed"?280:kind==="hit"?130:kind==="explode"?170:kind==="shoot"?720:190,b=kind==="seed"?1120:kind==="hit"?32:kind==="explode"?48:kind==="shoot"?260:430,d=kind==="seed"?.65:kind==="hit"?.5:kind==="explode"?.28:kind==="shoot"?.1:.15;o.frequency.setValueAtTime(a,now);o.frequency.exponentialRampToValueAtTime(b,now+d);g.gain.setValueAtTime(kind==="hit"?.14:kind==="explode"?.1:kind==="shoot"?.055:.07,now);g.gain.exponentialRampToValueAtTime(.001,now+d);o.start(now);o.stop(now+d+.03)}
  function alert(text){ui.alert.textContent=text;ui.alert.classList.add("show");state.alertTimer=1.6}
  function movement(){let x=input.stick.x,y=input.stick.y;for(const k of input.keys){if(k==="ArrowLeft"||k==="a")x--;if(k==="ArrowRight"||k==="d")x++;if(k==="ArrowUp"||k==="w")y--;if(k==="ArrowDown"||k==="s")y++}for(const d of input.touches.values()){if(d==="left")x--;if(d==="right")x++;if(d==="up")y--;if(d==="down")y++}const l=Math.hypot(x,y);return l>1?{x:x/l,y:y/l}:{x,y}}
  function lorentz(beta){return 1/Math.sqrt(Math.max(.015,1-beta*beta))}
  function resetStick(){input.stick.x=input.stick.y=0;input.stick.pointerId=null;ui.joystick.style.setProperty("--stick-x","0px");ui.joystick.style.setProperty("--stick-y","0px");ui.joystick.classList.remove("active")}
  function makeWell(x,forced){const rank=1+state.level*.14,blackChance=.18+state.level*.025;let type=forced||(state.level>0&&Math.random()<blackChance?"blackhole":Math.random()<.52?"galaxy":"moon"),radius=type==="blackhole"?rnd(36,49):type==="galaxy"?rnd(42,58):rnd(21,32),strength=(type==="blackhole"?1120000:type==="galaxy"?540000:88000)*rank;return{type,x,y:rnd(vh*.22,vh*.78),radius,strength,phase:rnd(0,TAU),target:false}}
  function makeHazard(x){const rank=1+state.level*.12,comet=Math.random()<Math.min(.44,.25+state.level*.035),scale=1+state.level*.035;return{kind:comet?"comet":"asteroid",x,y:rnd(72,vh-64),size:(comet?rnd(13,22):rnd(14,31))*scale,vx:(comet?rnd(-105,-58):rnd(-43,9))*rank,vy:rnd(-23,23)*rank,spin:rnd(0,TAU),rot:rnd(-3,3)}}
  function buildMission(){state.targetX=(4600+state.level*520)*3;state.nextHazard=680;state.nextWell=1050;state.hazards.length=state.wells.length=state.shots.length=state.particles.length=0;while(state.nextWell<state.targetX-820){state.wells.push(makeWell(state.nextWell));state.nextWell+=rnd(Math.max(760,1000-state.level*45),Math.max(930,1240-state.level*50))}const w=worlds[state.level];state.wells.push({type:"planet",x:state.targetX,y:rnd(vh*.31,vh*.7),radius:clamp(vh*.095,48,82),strength:185000,phase:0,target:true,world:w});while(state.nextHazard<state.targetX-320){state.hazards.push(makeHazard(state.nextHazard));state.nextHazard+=rnd(Math.max(115,205-state.level*15),Math.max(175,315-state.level*20))}}
  function resetMission(){state.time=state.proper=state.cam=0;state.intro=3.5;state.alertTimer=state.fireCooldown=0;state.player={x:vw*.3,y:vh*.52,vx:0,vy:0,beta:.18,angle:0,alive:true};input.keys.clear();input.touches.clear();input.fire=false;resetStick();buildMission();updateHud()}
  function begin(){resetMission();state.running=true;state.paused=false;state.loopToken++;state.last=performance.now();show(ui.menu,false);show(ui.over,false);show(ui.landed,false);show(ui.complete,false);show(ui.pause,false);show(ui.hud,true);ui.mobile.classList.toggle("active",coarse);ui.mobile.setAttribute("aria-hidden",String(!coarse));const token=state.loopToken;requestAnimationFrame(t=>loop(t,token));alert("MOVE FREELY · FIRE DESTROYS DEBRIS")}
  function start(){initAudio();state.level=0;state.seeded=0;begin()}
  function fail(reason){if(!state.running)return;state.running=false;state.loopToken++;state.player.alive=false;resetStick();sound("hit");burst(state.player.x,state.player.y,"#ff6889",32);const copy={debris:["COSMIC COLLISION","A fragment struck the expanded energy field."],blackhole:["EVENT HORIZON","The gravity well allowed no path back to the light."],galaxy:["GRAVITY CAPTURE","The galactic core pulled the mission off course."],moon:["SATELLITE IMPACT","A minor gravity centre became a major collision."],fast:["APPROACH TOO FAST","Relativistic inertia turned landing into impact."]}[reason]||["MISSION LOST","The seeds of life were lost in the dark."];ui.deathTitle.textContent=copy[0];ui.deathCopy.textContent=copy[1];show(ui.over,true);show(ui.hud,false);ui.mobile.classList.remove("active")}
  function seedWorld(){if(!state.running)return;state.running=false;state.loopToken++;state.seeded++;resetStick();sound("seed");burst(state.player.x,state.player.y,"#7dffd4",48);const w=worlds[state.level];ui.landedName.textContent=w.name;ui.landedCopy.textContent=w.copy;show(ui.landed,true);show(ui.hud,false);ui.mobile.classList.remove("active")}
  function nextWorld(){state.level++;if(state.level>=worlds.length){show(ui.landed,false);show(ui.complete,true);return}begin()}
  function burst(x,y,color,n){for(let i=0;i<n;i++){const a=rnd(0,TAU),s=rnd(25,150);state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rnd(.35,.9),max:.9,color,r:rnd(1.5,5)})}}
  function targetWell(){return state.wells[state.wells.length-1]}
  function collisionRadius(){const g=lorentz(state.player.beta);return clamp(18*(1+(g-1)*.64),18,55)}
  function fire(){if(!state.running||state.paused||state.fireCooldown>0)return;const p=state.player,wx=state.cam+p.x;let tx=1,ty=clamp(p.vy/460,-.36,.36),best=Infinity;for(const h of state.hazards){if(h.alive===false)continue;const dx=h.x-wx,dy=h.y-p.y,d=Math.hypot(dx,dy);if(dx>20&&dx<620&&Math.abs(dy)<220&&d<best){best=d;tx=dx/d;ty=dy/d}}state.shots.push({x:wx+32,y:p.y+ty*12,vx:920*tx,vy:920*ty,life:1.05});state.fireCooldown=.14;sound("shoot")}
  function update(dt){const p=state.player,m=movement();state.time+=dt;const gamma=lorentz(p.beta);state.proper+=dt/gamma;if(state.intro>0)state.intro=Math.max(0,state.intro-dt);state.fireCooldown=Math.max(0,state.fireCooldown-dt);p.landingCooldown=Math.max(0,(p.landingCooldown||0)-dt);p.beta=clamp(p.beta+m.x*.48*dt,.08,.9);const response=1-Math.exp(-16*dt);p.vx+=(m.x*270-p.vx)*response;p.vy+=(m.y*460-p.vy)*response;if(input.fire)fire();
    const target=targetWell(),targetScreen=target.x-state.cam;let scroll=(118+p.beta*430)*(state.intro>0?.32:1);if(targetScreen<vw*.84)scroll*=clamp((targetScreen-vw*.63)/(vw*.21),.035,1);state.cam+=scroll*dt;
    for(const w of state.wells){const sx=w.x-state.cam,dx=sx-p.x,dy=w.y-p.y,d=Math.hypot(dx,dy),massive=w.type==="blackhole"||w.type==="galaxy",capture=w.type==="blackhole"?2.65:w.type==="galaxy"?1.85:0,nearBoost=massive?1+clamp((w.radius*7-d)/(w.radius*7),0,1)*capture:1,a=w.strength*nearBoost/(d*d+6500);if(d<Math.max(vw,vh)*.62){p.vx+=dx/Math.max(1,d)*a*dt;p.vy+=dy/Math.max(1,d)*a*dt}if(!w.target&&d<w.radius+collisionRadius()*.32){fail(w.type);return}}
    p.x=clamp(p.x+p.vx*dt,vw*.13,vw*.74);p.y=clamp(p.y+p.vy*dt,70,vh-58);p.angle+=(clamp(p.vy/430,-.5,.5)-p.angle)*Math.min(1,dt*7);
    for(const h of state.hazards){if(h.alive===false)continue;h.x+=h.vx*dt;h.y+=h.vy*dt;h.spin+=h.rot*dt;const sx=h.x-state.cam;if(sx>-80&&sx<vw+80&&Math.hypot(sx-p.x,h.y-p.y)<h.size+collisionRadius()*.7){fail("debris");return}}
    for(const s of state.shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(const h of state.hazards){if(h.alive===false||s.life<=0)continue;if(Math.hypot(s.x-h.x,s.y-h.y)<h.size+8){h.alive=false;s.life=0;sound("explode");burst(h.x-state.cam,h.y,h.kind==="comet"?"#7df5ff":"#ffbc72",22)}}}
    const tx=target.x-state.cam,td=Math.hypot(tx-p.x,target.y-p.y);if(td<target.radius+collisionRadius()*.5){if(p.beta<=.5&&Math.hypot(p.vx,p.vy)<210){seedWorld();return}if(!p.landingCooldown){p.landingCooldown=.55;p.x-=18;p.vx=-105;p.beta=Math.max(.12,p.beta*.72);alert("TOO FAST · HOLD LEFT, THEN TOUCH THE PLANET")}}
    state.particles.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=Math.pow(.08,dt);q.vy*=Math.pow(.08,dt);q.life-=dt});state.particles=state.particles.filter(q=>q.life>0);if(m.x>0||Math.abs(m.y)>.15)for(let i=0;i<2;i++)state.particles.push({x:p.x-rnd(28,42),y:p.y+rnd(-8,8),vx:rnd(-95,-45),vy:rnd(-20,20),life:rnd(.18,.42),max:.42,color:p.beta>.7?"#bd76ff":"#6ff7ff",r:rnd(1,3.5)});
    state.shots=state.shots.filter(s=>s.life>0&&s.x-state.cam<vw+100);state.hazards=state.hazards.filter(h=>h.alive!==false&&h.x-state.cam>-110);if(gamma>1.5)ui.warning.classList.add("show");else ui.warning.classList.remove("show");if(state.alertTimer>0&&(state.alertTimer-=dt)<=0)ui.alert.classList.remove("show");const remaining=target.x-state.cam;if(remaining<vw*1.25&&remaining>vw*.82&&state.alertTimer<=0)alert("LANDING: HOLD LEFT BELOW 0.50 c · TOUCH THE GLOWING PLANET");updateHud()}
  function updateHud(){if(!state.player)return;const w=worlds[state.level],g=lorentz(state.player.beta),progress=clamp(state.cam/state.targetX,0,1);ui.target.textContent=w.name;ui.speed.textContent=state.player.beta.toFixed(2)+" c";ui.gamma.textContent=g.toFixed(2);ui.seeds.textContent=state.seeded+" / "+worlds.length;ui.distance.style.width=Math.round(progress*100)+"%";ui.distanceLabel.textContent=w.name+" · "+Math.round(progress*100)+"%"}
  function drawBackground(){ctx.setTransform(dpr,0,0,dpr,0,0);const hue=(245+state.level*17)%360,g=ctx.createRadialGradient(vw*.72,vh*.35,20,vw*.5,vh*.5,Math.max(vw,vh));g.addColorStop(0,`hsl(${hue} 67% 18%)`);g.addColorStop(.48,"#070925");g.addColorStop(1,"#02020d");ctx.fillStyle=g;ctx.fillRect(0,0,vw,vh);for(const s of state.stars){const x=((s.x-state.cam*s.p)%(vw+20)+vw+20)%(vw+20)-10,twinkle=.55+Math.sin(state.time*(1+s.p*5)+s.x)*.35;ctx.globalAlpha=twinkle;ctx.fillStyle=s.c;ctx.beginPath();ctx.arc(x,s.y,s.r,0,TAU);ctx.fill()}ctx.globalAlpha=1;const ng=ctx.createRadialGradient(vw*.15,vh*.74,0,vw*.15,vh*.74,vw*.42);ng.addColorStop(0,"rgba(31,221,255,.08)");ng.addColorStop(1,"rgba(10,20,80,0)");ctx.fillStyle=ng;ctx.fillRect(0,0,vw,vh)}
  function visibleWells(){return state.wells.filter(w=>{const x=w.x-state.cam;return x>-300&&x<vw+300})}
  function warped(x,y,wells){let px=x,py=y;for(const w of wells){const wx=w.x-state.cam,dx=wx-px,dy=w.y-py,d2=dx*dx+dy*dy,pull=clamp((w.target?2500:w.type==="blackhole"?10500:w.type==="galaxy"?6900:1100)/(d2+850),0,w.type==="blackhole"?.74:w.type==="galaxy"?.66:.48);px+=dx*pull;py+=dy*pull}return{x:px,y:py}}
  function drawGrid(){const wells=visibleWells(),step=coarse?35:31;for(const w of wells){const x=w.x-state.cam,r=w.radius*(w.type==="blackhole"?4.6:w.type==="galaxy"?4.1:3.1),g=ctx.createRadialGradient(x,w.y,0,x,w.y,r);g.addColorStop(0,w.target?"rgba(90,255,211,.14)":w.type==="blackhole"?"rgba(155,80,255,.24)":"rgba(74,221,255,.14)");g.addColorStop(.48,w.type==="blackhole"?"rgba(96,70,210,.1)":"rgba(54,193,225,.07)");g.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,w.y,r,0,TAU);ctx.fill()}ctx.lineWidth=.82;ctx.strokeStyle="rgba(92,225,255,.21)";for(let gy=-step;gy<vh+step;gy+=step){ctx.beginPath();for(let x=-step;x<vw+step;x+=8){const p=warped(x,gy,wells);x===-step?ctx.moveTo(p.x,p.y):ctx.lineTo(p.x,p.y)}ctx.stroke()}ctx.strokeStyle="rgba(171,104,255,.16)";const offset=-((state.cam*.22)%step);for(let gx=offset-step;gx<vw+step;gx+=step){ctx.beginPath();for(let y=-step;y<vh+step;y+=8){const p=warped(gx,y,wells);y===-step?ctx.moveTo(p.x,p.y):ctx.lineTo(p.x,p.y)}ctx.stroke()}for(const w of wells){const x=w.x-state.cam;ctx.save();ctx.translate(x,w.y);ctx.strokeStyle=w.target?"rgba(108,255,211,.32)":w.type==="blackhole"?"rgba(206,112,255,.42)":"rgba(92,232,255,.29)";ctx.lineWidth=w.type==="blackhole"?1.25:1;for(let i=1;i<=5;i++){ctx.globalAlpha=.86-i*.12;ctx.beginPath();ctx.ellipse(0,0,w.radius*(1.12+i*.58),w.radius*(.5+i*.31),-.18,0,TAU);ctx.stroke()}ctx.restore()}}
  function drawPlanet(w,x,y){const r=w.radius,c=w.world||worlds[state.level];ctx.save();ctx.translate(x,y);if(c.rings){ctx.strokeStyle="rgba(226,225,255,.5)";ctx.lineWidth=r*.16;ctx.beginPath();ctx.ellipse(0,0,r*1.65,r*.39,-.13,0,TAU);ctx.stroke();ctx.strokeStyle="rgba(126,207,255,.34)";ctx.lineWidth=r*.07;ctx.beginPath();ctx.ellipse(0,0,r*1.9,r*.48,-.13,0,TAU);ctx.stroke()}const g=ctx.createRadialGradient(-r*.34,-r*.38,r*.08,0,0,r);g.addColorStop(0,c.accent);g.addColorStop(.45,c.color);g.addColorStop(1,c.dark);ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,r,0,TAU);ctx.fill();ctx.save();ctx.clip();if(c.bands){for(let i=-3;i<=3;i++){ctx.fillStyle=i%2?"rgba(255,255,255,.12)":"rgba(20,5,45,.13)";ctx.fillRect(-r,i*r*.23,r*2,r*.11)}}ctx.restore();ctx.strokeStyle="rgba(181,250,255,.58)";ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,r+8+Math.sin(state.time*2)*2,0,TAU);ctx.stroke();ctx.restore()}
  function drawWell(w){const x=w.x-state.cam,y=w.y,r=w.radius;if(w.target){drawPlanet(w,x,y);ctx.fillStyle=state.player&&state.player.beta<=.5?"#8effd4":"#ffd06a";ctx.font="900 10px ui-monospace,monospace";ctx.textAlign="center";ctx.fillText(state.player&&state.player.beta<=.5?"SAFE SPEED · TOUCH TO LAND":"HOLD LEFT · SLOW BELOW 0.50 c",x,y-r-20);return}ctx.save();ctx.translate(x,y);if(w.type==="blackhole"){const g=ctx.createRadialGradient(0,0,1,0,0,r*1.9);g.addColorStop(0,"#000");g.addColorStop(.36,"#000");g.addColorStop(.47,"#ffbf57");g.addColorStop(.62,"rgba(167,67,255,.48)");g.addColorStop(1,"rgba(43,24,117,0)");ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,r*1.9,0,TAU);ctx.fill();ctx.rotate(-.24);ctx.strokeStyle="rgba(255,203,104,.72)";ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(0,0,r*1.7,r*.42,0,0,TAU);ctx.stroke()}else if(w.type==="galaxy"){ctx.rotate(state.time*.05+w.phase);for(let i=0;i<5;i++){ctx.strokeStyle=i%2?"rgba(119,230,255,.45)":"rgba(189,112,255,.48)";ctx.lineWidth=6-i*.75;ctx.beginPath();ctx.ellipse(0,0,r*(.4+i*.24),r*(.14+i*.09),i*.5,0,TAU);ctx.stroke()}ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(0,0,6,0,TAU);ctx.fill()}else{const g=ctx.createRadialGradient(-r*.3,-r*.3,2,0,0,r);g.addColorStop(0,"#d6e6f2");g.addColorStop(1,"#3f526f");ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,r,0,TAU);ctx.fill()}ctx.restore()}
  function drawHazard(h){const x=h.x-state.cam;if(x<-90||x>vw+90)return;ctx.save();ctx.translate(x,h.y);ctx.rotate(h.spin);if(h.kind==="comet"){const g=ctx.createLinearGradient(-h.size*5,0,h.size,0);g.addColorStop(0,"rgba(82,132,255,0)");g.addColorStop(.72,"rgba(103,229,255,.42)");g.addColorStop(1,"#fff");ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(-h.size*5,-h.size*.34);ctx.lineTo(h.size*.45,-h.size*.66);ctx.lineTo(h.size*.45,h.size*.66);ctx.lineTo(-h.size*5,h.size*.34);ctx.closePath();ctx.fill()}const g=ctx.createRadialGradient(-h.size*.3,-h.size*.3,1,0,0,h.size);g.addColorStop(0,h.kind==="comet"?"#e8ffff":"#b99b85");g.addColorStop(1,h.kind==="comet"?"#4b88ff":"#413549");ctx.fillStyle=g;ctx.beginPath();for(let i=0;i<10;i++){const a=i/10*TAU,rr=h.size*(.8+(i%3)*.11);ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr)}ctx.closePath();ctx.fill();ctx.restore()}
  function drawShots(){ctx.save();ctx.globalCompositeOperation="lighter";for(const s of state.shots){const x=s.x-state.cam;if(x<-20||x>vw+40)continue;const g=ctx.createLinearGradient(x-35,s.y,x+12,s.y);g.addColorStop(0,"rgba(101,248,255,0)");g.addColorStop(.45,"#73f9ff");g.addColorStop(1,"#fff5a8");ctx.strokeStyle=g;ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(x-34,s.y);ctx.lineTo(x+12,s.y);ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(x+12,s.y,4,0,TAU);ctx.fill()}ctx.restore()}
  function drawParticles(){for(const q of state.particles){ctx.globalAlpha=clamp(q.life/q.max,0,1);ctx.fillStyle=q.color;ctx.beginPath();ctx.arc(q.x,q.y,q.r,0,TAU);ctx.fill()}ctx.globalAlpha=1}
  function drawPlayer(){const p=state.player;if(!p)return;const g=lorentz(p.beta),field=collisionRadius(),h=clamp(vh*.115,66,104),w=h*1.25;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);const halo=ctx.createRadialGradient(0,0,field*.2,0,0,field*1.45);halo.addColorStop(0,"rgba(96,245,255,.05)");halo.addColorStop(.62,p.beta>.72?"rgba(184,87,255,.18)":"rgba(84,225,255,.12)");halo.addColorStop(1,"rgba(124,82,255,0)");ctx.fillStyle=halo;ctx.beginPath();ctx.arc(0,0,field*1.45,0,TAU);ctx.fill();ctx.strokeStyle=p.beta>.72?"rgba(255,120,186,.65)":"rgba(105,244,255,.48)";ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,field,0,TAU);ctx.stroke();ctx.scale(1/g,1);ctx.filter="drop-shadow(0 8px 9px rgba(0,0,0,.65)) drop-shadow(0 0 8px rgba(88,224,255,.28))";if(astronaut.complete&&astronaut.naturalWidth)ctx.drawImage(astronaut,-w/2,-h/2,w,h);else{ctx.fillStyle="#eef6ff";ctx.beginPath();ctx.arc(0,0,h*.25,0,TAU);ctx.fill()}ctx.restore()}
  function drawIntro(){if(!state.player||state.intro<=0||!mothership.complete||!mothership.naturalWidth)return;const progress=1-state.intro/3.5,w=Math.min(vw*.52,560),h=w*.5,x=vw*.08-progress*vw*.22,y=vh*.5;ctx.save();ctx.globalAlpha=clamp(state.intro,0,1);ctx.filter="drop-shadow(0 16px 18px rgba(0,0,0,.7))";ctx.drawImage(mothership,x-w*.62,y-h*.5,w,h);ctx.restore()}
  function draw(){drawBackground();drawGrid();for(const w of visibleWells())drawWell(w);for(const h of state.hazards)drawHazard(h);drawShots();drawIntro();drawParticles();drawPlayer();if(state.running&&state.player){const g=lorentz(state.player.beta);ctx.fillStyle="rgba(195,222,255,.54)";ctx.font="700 9px ui-monospace,monospace";ctx.textAlign="right";ctx.fillText(`MISSION TIME ${state.time.toFixed(1)} s  ·  SUIT TIME ${state.proper.toFixed(1)} s  ·  LENGTH ${(1/g).toFixed(2)} L₀`,vw-16,vh-15)}}
  function loop(now,token){if(token!==state.loopToken||!state.running||state.paused)return;const dt=Math.min(.033,Math.max(.001,(now-state.last)/1000));state.last=now;update(dt);draw();if(state.running&&!state.paused&&token===state.loopToken)requestAnimationFrame(t=>loop(t,token))}
  function pause(){if(!state.running)return;state.paused=true;input.keys.clear();input.touches.clear();input.fire=false;ui.fire.classList.remove("active");resetStick();show(ui.pause,true);ui.mobile.classList.remove("active")}
  function resume(){if(!state.running)return;state.paused=false;show(ui.pause,false);ui.mobile.classList.toggle("active",coarse);state.last=performance.now();const token=state.loopToken;requestAnimationFrame(t=>loop(t,token))}
  function menu(){state.running=false;state.paused=false;state.loopToken++;input.keys.clear();input.touches.clear();input.fire=false;ui.fire.classList.remove("active");resetStick();show(ui.menu,true);show(ui.over,false);show(ui.landed,false);show(ui.complete,false);show(ui.pause,false);show(ui.hud,false);ui.warning.classList.remove("show");ui.mobile.classList.remove("active");draw()}
  addEventListener("resize",resize,{passive:true});addEventListener("keydown",e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown","w","a","s","d"].includes(k)){e.preventDefault();input.keys.add(k)}if([" ","x","v"].includes(k)){e.preventDefault();input.fire=true;fire()}if(k==="Escape"&&state.running)(state.paused?resume:pause)()});addEventListener("keyup",e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;input.keys.delete(k);if([" ","x","v"].includes(k))input.fire=false});addEventListener("blur",()=>{input.keys.clear();input.fire=false;resetStick();if(!coarse&&state.running&&!state.paused)pause()});document.addEventListener("visibilitychange",()=>{if(document.hidden&&state.running&&!state.paused)pause()});
  document.querySelectorAll("[data-dir]").forEach(btn=>{const release=e=>{input.touches.delete(e.pointerId);btn.classList.remove("active")};btn.addEventListener("pointerdown",e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);input.touches.set(e.pointerId,btn.dataset.dir);btn.classList.add("active")});btn.addEventListener("pointerup",release);btn.addEventListener("pointercancel",release);btn.addEventListener("lostpointercapture",release)});
  const moveStick=e=>{if(e.pointerId!==input.stick.pointerId)return;const r=ui.joystick.getBoundingClientRect(),rad=r.width*.34,dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),len=Math.hypot(dx,dy)||1,s=Math.min(1,rad/len),sx=dx*s,sy=dy*s;input.stick.x=sx/rad;input.stick.y=sy/rad;ui.joystick.style.setProperty("--stick-x",sx+"px");ui.joystick.style.setProperty("--stick-y",sy+"px")};
  ui.joystick.addEventListener("pointerdown",e=>{e.preventDefault();input.stick.pointerId=e.pointerId;ui.joystick.setPointerCapture(e.pointerId);ui.joystick.classList.add("active");moveStick(e)});ui.joystick.addEventListener("pointermove",moveStick);ui.joystick.addEventListener("pointerup",resetStick);ui.joystick.addEventListener("pointercancel",resetStick);ui.joystick.addEventListener("lostpointercapture",resetStick);
  const releaseFire=()=>{input.fire=false;ui.fire.classList.remove("active")};ui.fire.addEventListener("pointerdown",e=>{e.preventDefault();ui.fire.setPointerCapture(e.pointerId);input.fire=true;ui.fire.classList.add("active");fire()});ui.fire.addEventListener("pointerup",releaseFire);ui.fire.addEventListener("pointercancel",releaseFire);ui.fire.addEventListener("lostpointercapture",releaseFire);
  ui.play.addEventListener("click",start);ui.retry.addEventListener("click",begin);ui.home.addEventListener("click",menu);ui.next.addEventListener("click",nextWorld);ui.again.addEventListener("click",start);ui.completeHome.addEventListener("click",menu);ui.pauseBtn.addEventListener("click",pause);ui.resume.addEventListener("click",resume);ui.quit.addEventListener("click",menu);
  if(new URLSearchParams(location.search).has("test"))window.__LIFEBEARER_DIAGNOSTICS__=()=>{const t=targetWell();return{running:state.running,paused:state.paused,level:state.level,seeded:state.seeded,cam:state.cam,targetX:state.targetX,target:t?{x:t.x-state.cam,y:t.y,radius:t.radius}:null,player:state.player?{x:state.player.x,y:state.player.y,beta:state.player.beta,gamma:lorentz(state.player.beta),field:collisionRadius()}:null,stick:{x:input.stick.x,y:input.stick.y},firing:input.fire,shots:state.shots.length,hazards:state.hazards.length,wells:state.wells.map(w=>({type:w.type,target:w.target,radius:w.radius}))}};
  resize();draw();
})();
