const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function harness(options={}){
 class El{
  constructor(id=''){this.id=id;this.listeners={};this.dataset={};this.attributes={};this.hidden=false;this.disabled=false;this.open=false;this.children=[];this.queries={};const c=new Set();this.classList={add:n=>c.add(n),remove:n=>c.delete(n),contains:n=>c.has(n),toggle:(n,on)=>on?c.add(n):c.delete(n)};}
  addEventListener(n,f){(this.listeners[n]||=[]).push(f);}
  emit(n,e={}){const event={preventDefault(){},pointerId:1,clientX:100,clientY:100,key:'',...e};for(const f of this.listeners[n]||[])f(event);}
  click(){if(this.disabled)return;const result=this.onclick?.();this.emit('click',{detail:0});return result;}
  setAttribute(name,value){this.attributes[name]=value;}
  querySelector(s){return this.queries[s]??=new El();}
  getContext(){return new Proxy({},{get:()=>()=>{}});}
  getBoundingClientRect(){return this.id==='next'?{width:170,height:50}:doc.body.classList.contains('immersive')?{width:370,height:620}:{width:340,height:480};}
  setPointerCapture(){}showModal(){this.open=true;}close(){this.open=false;this.emit('close');}
 }
 const elements=new Map(),get=id=>{if(!elements.has(id))elements.set(id,new El(id));return elements.get(id);};get('charge').children=Array.from({length:4},()=>new El());
 const modes=['flow','chill'].map(mode=>{const e=new El();e.dataset.mode=mode;return e;}),actions=['left','rotate','right','drop'].map(action=>{const e=new El();e.dataset.action=action;return e;});
 const doc=new El();doc.hidden=false;doc.body=new El();doc.documentElement=new El();doc.getElementById=get;doc.querySelectorAll=s=>s==='[data-mode]'?modes:actions;
 if(options.fullscreen){doc.documentElement.requestFullscreen=async()=>{if(options.fullscreen==='reject')throw Error('unsupported');doc.fullscreenElement=doc.documentElement;doc.emit('fullscreenchange');};doc.exitFullscreen=async()=>{doc.fullscreenElement=null;doc.emit('fullscreenchange');};}
 const win=new El(),frames=[],timers=new Map(),audio=[];let now=0,id=0;
 if(options.audio)win.AudioContext=class{
  constructor(){this.currentTime=0;this.state='suspended';this.nodes=new Set();this.played=[];audio.push(this);}
  resume(){this.state='running';return Promise.resolve();}
  createGain(){return {gain:{value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}};}
  createOscillator(){const c=this,o={frequency:{value:0},connect(){},disconnect(){c.nodes.delete(o);},start(t){c.played.push({t,f:o.frequency.value});},stop(t=c.currentTime){o.end=t;if(t<=c.currentTime)o.onended?.();}};c.nodes.add(o);return o;}
  advance(t){this.currentTime=t;for(const o of [...this.nodes])if(o.end<=t)o.onended?.();}
 };
 const storage=options.storage||{getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}};
 const context={console,document:doc,window:win,Micio:require('../engine.js'),MicioDraw:require('../draw.js'),matchMedia:()=>({matches:false}),devicePixelRatio:2,performance:{now:()=>now},localStorage:storage,requestAnimationFrame:f=>frames.push(f),setTimeout:f=>{timers.set(++id,f);return id;},setInterval:f=>{timers.set(++id,f);return id;},clearTimeout:i=>timers.delete(i),clearInterval:i=>timers.delete(i)};
 let source=fs.readFileSync(path.join(__dirname,'../game.js'),'utf8');const anchor='  resize();welcome();requestAnimationFrame(loop);';assert.ok(source.includes(anchor));source=source.replace(anchor,'  window.test={game,act,start,resize,sound,get paused(){return paused;},get drag(){return drag;}};'+anchor);vm.createContext(context);vm.runInContext(source,context);
 return {g:win.test,get,doc,win,modes,actions,timers,audio,frame(ms=16){now+=ms;for(const a of audio)a.advance(now/1000);const ready=frames.splice(0);ready.forEach(f=>f(now));}};
}
test('welcome pauses; default play starts a visible countdown and automatic falling',()=>{const h=harness();assert.equal(h.g.paused,true);h.frame(10000);h.g.act('drop');assert.equal(h.g.game.moves,0);assert.equal(h.g.game.elapsed,0);h.get('dialog-main').click();assert.equal(h.g.paused,false);const r=h.g.game.active.r;h.frame();h.frame(1200);assert.ok(h.g.game.active.r>r);assert.equal(h.get('timer').textContent,'2:59');assert.equal(h.g.game.elapsed,1200);});
test('relax remains available by choice, without automatic falling or a deadline',()=>{const h=harness();h.get('dialog-secondary').click();const r=h.g.game.active.r;for(let i=0;i<200;i++)h.frame(1000);assert.equal(h.g.game.active.r,r);assert.equal(h.g.game.over,false);assert.equal(h.get('timer').textContent,'∞');h.doc.emit('keydown',{key:' '});assert.equal(h.g.game.moves,1);h.modes[0].click();h.get('dialog-main').click();assert.equal(h.g.game.mode,'flow');assert.equal(h.get('timer').textContent,'3:00');});
test('explicit and hidden-page pause stop both timer and pieces, with no resume jump',()=>{const h=harness();h.get('dialog-main').click();h.frame();h.frame(1200);h.get('pause').click();const still=h.g.game.active.r,elapsed=h.g.game.elapsed;h.frame(30000);assert.equal(h.g.game.active.r,still);assert.equal(h.g.game.elapsed,elapsed);h.get('dialog-main').click();h.frame();h.frame(500);assert.equal(h.g.game.elapsed,elapsed+500);h.doc.hidden=true;h.doc.emit('visibilitychange');h.frame(40000);assert.equal(h.g.paused,true);assert.equal(h.g.game.elapsed,elapsed+500);h.doc.hidden=false;h.doc.emit('visibilitychange');assert.equal(h.get('dialog').open,true);});
test('deadline shows a result and locks controls; retry restores a fresh three minutes',()=>{const h=harness();h.get('dialog-main').click();h.frame();h.g.game.advance(179500);h.frame(500);assert.equal(h.g.game.endReason,'time');assert.equal(h.get('timer').textContent,'0:00');assert.equal(h.get('dialog-title').textContent,'Tempo scaduto!');h.doc.emit('keydown',{key:' '});assert.equal(h.g.game.moves,0);h.frame(10000);assert.equal(h.g.game.elapsed,180000);h.get('dialog-main').click();assert.equal(h.g.game.over,false);assert.equal(h.g.paused,false);assert.equal(h.get('timer').textContent,'3:00');});
test('a long rendered frame counts real time, and early top-out shows game over',()=>{const h=harness();h.get('dialog-main').click();h.frame();h.frame(4000);assert.equal(h.g.game.elapsed,4000);for(let i=0;i<100&&!h.g.game.over;i++)h.g.act('drop');assert.equal(h.g.game.endReason,'full');assert.equal(h.get('dialog-kicker').textContent,'FINE PARTITA');assert.ok(h.g.game.remaining>0);const score=h.g.game.score;h.g.act('drop');assert.equal(h.g.game.score,score);});
test('touch drag moves, tap rotates, drop button places and cancellation clears state',()=>{const h=harness();h.get('dialog-main').click();const c=h.get('board'),q=h.g.game.active.q;c.emit('pointerdown');c.emit('pointermove',{clientX:170});assert.ok(h.g.game.active.q>q);c.emit('pointerup',{clientX:170});assert.equal(h.g.drag,null);const shape=JSON.stringify(h.g.game.active.cells);c.emit('pointerdown');c.emit('pointerup');assert.notEqual(JSON.stringify(h.g.game.active.cells),shape);c.emit('pointerdown');c.emit('pointercancel');assert.equal(h.g.drag,null);h.actions[3].click();assert.equal(h.g.game.moves,1);});
test('held buttons stop on cancellation and restart confirmation preserves or resets the game',()=>{const h=harness();h.get('dialog-main').click();h.actions[0].emit('pointerdown');assert.ok(h.timers.size);h.actions[0].emit('pointercancel');assert.equal(h.timers.size,0);h.g.act('drop');h.get('restart').click();assert.equal(h.g.paused,true);h.get('dialog-secondary').click();assert.equal(h.g.game.moves,1);h.get('restart').click();h.get('dialog-main').click();assert.equal(h.g.game.moves,0);assert.equal(h.g.paused,false);});
test('native fullscreen is opt-in, resizes the canvas, and browser exit restores the layout',async()=>{const h=harness({fullscreen:'native'});assert.equal(h.doc.body.classList.contains('immersive'),false);await h.get('dialog-fullscreen').click();assert.equal(h.g.paused,true);assert.equal(h.doc.fullscreenElement,h.doc.documentElement);h.frame();assert.equal(h.get('board').width,740);assert.equal(h.get('board').height,1240);h.get('dialog-main').click();h.g.act('drop');const score=h.g.game.score;await h.get('fullscreen').click();h.frame();assert.equal(h.doc.body.classList.contains('immersive'),false);assert.equal(h.get('board').width,680);assert.equal(h.g.game.score,score);await h.get('fullscreen').click();await h.doc.exitFullscreen();assert.equal(h.get('fullscreen').attributes['aria-pressed'],'false');});
test('unsupported or rejected fullscreen keeps a usable extended view with an exit',async()=>{for(const fullscreen of [undefined,'reject']){const h=harness({fullscreen});h.get('dialog-main').click();h.g.act('drop');await h.get('fullscreen').click();assert.equal(h.doc.body.classList.contains('immersive'),true);assert.equal(h.get('screen-status').hidden,false);assert.equal(h.g.game.moves,1);assert.equal(h.g.paused,false);h.doc.emit('keydown',{key:'Escape'});assert.equal(h.doc.body.classList.contains('immersive'),false);}});
test('music starts on the play gesture, plays a melody, pauses, resumes and mutes cleanly',()=>{const h=harness({audio:true});assert.equal(h.audio.length,0);h.get('dialog-main').click();assert.equal(h.audio.length,1);for(let i=0;i<250;i++)h.frame();const a=h.audio[0];assert.ok(a.played.length>20);assert.ok(new Set(a.played.map(n=>n.f)).size>5);assert.ok(h.g.sound.voices.size<=16);h.get('pause').click();assert.equal(h.g.sound.voices.size,0);const n=a.played.length;h.frame(1000);assert.equal(a.played.length,n);h.get('dialog-main').click();h.frame();assert.ok(a.played.length>n);h.get('sound').click();assert.equal(h.g.sound.on,false);assert.equal(h.g.sound.voices.size,0);const muted=a.played.length;for(let i=0;i<100;i++)h.frame();assert.equal(a.played.length,muted);assert.equal(h.get('sound').attributes['aria-pressed'],'false');});
test('a saved mute preference is respected and unavailable audio never breaks play',()=>{const h=harness({audio:true,storage:{getItem:key=>key==='micio-music'?'off':null,setItem(){}}});h.get('dialog-main').click();h.frame();assert.equal(h.audio.length,0);h.get('sound').click();h.frame();assert.equal(h.audio.length,1);const noAudio=harness();noAudio.get('dialog-main').click();noAudio.get('sound').click();noAudio.get('sound').click();assert.equal(noAudio.g.paused,false);noAudio.g.act('drop');assert.equal(noAudio.g.game.moves,1);});
test('canvas resolution stays capped and blocked localStorage does not prevent scoring',()=>{const h=harness();assert.equal(h.get('board').width,680);assert.equal(h.get('board').height,960);h.get('dialog-main').click();h.g.act('drop');assert.ok(Number(h.get('score').textContent)>0);h.g.resize();h.frame();});
