const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function harness(){
 class El{constructor(id=''){this.id=id;this.listeners={};this.dataset={};this.hidden=false;this.disabled=false;this.open=false;this.children=[];const c=new Set();this.classList={add:n=>c.add(n),remove:n=>c.delete(n),toggle:(n,on)=>on?c.add(n):c.delete(n)};}addEventListener(n,f){(this.listeners[n]||=[]).push(f);}emit(n,e={}){const event={preventDefault(){},pointerId:1,clientX:100,clientY:100,key:'',...e};for(const f of this.listeners[n]||[])f(event);}click(){if(this.disabled)return;if(this.onclick)this.onclick();this.emit('click',{detail:0});}setAttribute(){}querySelector(){return new El();}getContext(){return new Proxy({},{get:()=>()=>{}});}getBoundingClientRect(){return {width:this.id==='next'?170:340,height:this.id==='next'?50:480};}setPointerCapture(){}showModal(){this.open=true;}close(){this.open=false;this.emit('close');}}
 const elements=new Map(),get=id=>{if(!elements.has(id))elements.set(id,new El(id));return elements.get(id);};get('charge').children=Array.from({length:4},()=>new El());
 const modes=['chill','flow'].map(mode=>{const e=new El();e.dataset.mode=mode;return e;}),actions=['left','rotate','right','drop'].map(action=>{const e=new El();e.dataset.action=action;return e;});
 const doc=new El();doc.hidden=false;doc.getElementById=get;doc.querySelectorAll=s=>s==='[data-mode]'?modes:actions;
 const win=new El(),frames=[],timers=new Map();let now=0,id=0;
 const context={console,document:doc,window:win,Micio:require('../engine.js'),MicioDraw:require('../draw.js'),matchMedia:()=>({matches:false}),devicePixelRatio:2,performance:{now:()=>now},localStorage:{getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}},requestAnimationFrame:f=>frames.push(f),setTimeout:f=>{timers.set(++id,f);return id;},setInterval:f=>{timers.set(++id,f);return id;},clearTimeout:i=>timers.delete(i),clearInterval:i=>timers.delete(i)};
 let source=fs.readFileSync(path.join(__dirname,'../game.js'),'utf8');source=source.replace('  resize();help();requestAnimationFrame(loop);','  window.test={game,act,start,resize,get paused(){return paused;},get drag(){return drag;}};resize();help();requestAnimationFrame(loop);');vm.createContext(context);vm.runInContext(source,context);
 return {g:win.test,get,doc,win,modes,actions,timers,frame(ms=16){now+=ms;const ready=frames.splice(0);ready.forEach(f=>f(now));}};
}
test('welcome pauses; start and default relax mode do not auto-drop',()=>{const h=harness();assert.equal(h.g.paused,true);const r=h.g.game.active.r;h.g.act('drop');assert.equal(h.g.game.moves,0);h.get('dialog-main').click();assert.equal(h.g.paused,false);for(let i=0;i<200;i++)h.frame();assert.equal(h.g.game.active.r,r);h.doc.emit('keydown',{key:' '});assert.equal(h.g.game.moves,1);});
test('flow falls, and explicit or hidden-page pause stops it',()=>{const h=harness();h.get('dialog-main').click();h.modes[1].click();const r=h.g.game.active.r;for(let i=0;i<120;i++)h.frame();assert.ok(h.g.game.active.r>r);h.get('pause').click();const still=h.g.game.active.r;for(let i=0;i<150;i++)h.frame();assert.equal(h.g.game.active.r,still);h.get('dialog-main').click();h.doc.hidden=true;h.doc.emit('visibilitychange');assert.equal(h.g.paused,true);assert.equal(h.get('dialog').open,true);});
test('touch drag moves, tap rotates, drop button places and pointer cancellation clears state',()=>{const h=harness();h.get('dialog-main').click();const c=h.get('board'),q=h.g.game.active.q;c.emit('pointerdown');c.emit('pointermove',{clientX:170});assert.ok(h.g.game.active.q>q);c.emit('pointerup',{clientX:170});assert.equal(h.g.drag,null);const shape=JSON.stringify(h.g.game.active.cells);c.emit('pointerdown');c.emit('pointerup');assert.notEqual(JSON.stringify(h.g.game.active.cells),shape);c.emit('pointerdown');c.emit('pointercancel');assert.equal(h.g.drag,null);h.actions[3].click();assert.equal(h.g.game.moves,1);});
test('held buttons stop on cancellation and restart confirmation preserves or resets the game',()=>{const h=harness();h.get('dialog-main').click();h.actions[0].emit('pointerdown');assert.ok(h.timers.size);h.actions[0].emit('pointercancel');assert.equal(h.timers.size,0);h.g.act('drop');h.get('restart').click();assert.equal(h.g.paused,true);h.get('dialog-secondary').click();assert.equal(h.g.game.moves,1);h.get('restart').click();h.get('dialog-main').click();assert.equal(h.g.game.moves,0);assert.equal(h.g.paused,false);});
test('canvas backing size is capped and UI works when localStorage is blocked',()=>{const h=harness();assert.equal(h.get('board').width,680);assert.equal(h.get('board').height,960);h.get('dialog-main').click();h.g.act('drop');assert.ok(Number(h.get('score').textContent)>0);h.g.resize();h.frame();});
